import { readCharterTemplate } from "../content/charter.ts";
import { verificationGatesFor } from "../detect/verificationGates.ts";
import type { PackageEntry } from "../types/detect.ts";
import type { SetupManifest } from "../types/manifest.ts";
import type { Tool } from "../types/core.ts";
import { planPerPackageOutputs } from "./monorepoPlan.ts";
import {
  detectionContextFromManifest,
  substituteRepoTokens,
  substituteVerificationGateTokens,
  type VerificationGateSet,
} from "./substitution.ts";

/**
 * Core `AGENTS.md` renderer — the standards-first charter emission.
 *
 * The engine renders the root `AGENTS.md` ONCE, from the bundled charter
 * template plus the manifest's persisted facts, and every client consumes that
 * one file: three of the four target tools read `AGENTS.md` natively, and the
 * fourth bridges to it from its own entry file. The invariant that buys is
 * narrower than "adapters carry no charter logic", and stating it too broadly
 * hid a real caller: NO ADAPTER RE-RENDERS THE CHARTER. `codex` alone appends
 * to it, through the shared-path replacement contract
 * (`AdapterOutput.replacesSharedPath`) — it passes this render in as the `head`
 * of its own appendix and measures the combined body against its 32 KiB
 * `AGENTS.md` budget. That is a re-use of the one render, which is what the
 * invariant protects; a second render, or a post-processed charter body, would
 * be the duplicated core responsibility this module rules out.
 *
 * The emitted body is the charter template with its frontmatter stripped and
 * every substitution token resolved. Frontmatter is corpus metadata (id, load
 * class, obsolete-when trigger) — a client-facing standards file is plain
 * markdown with no such head, so the split happens here rather than asking
 * each consumer to skip it.
 *
 * Pure planning, like the rest of `src/emit/`: this module reads the template
 * and returns data — content, measurements, per-package targets. Writing,
 * merge policy and ledger rows stay with the caller. Nothing here reads a
 * clock, so two renders over the same template and manifest are byte-identical
 * and drift detection can compare regenerated bytes against disk.
 */

/** Filename of the emitted charter, at the repo root and inside each planned package. */
export const AGENTS_MD_FILE = "AGENTS.md";

/**
 * The slice of the CLI's emission context this renderer reads. Structurally
 * compatible with that context on purpose — the emission planner passes its
 * context through unchanged — but declared here as its own type because the
 * engine never imports the CLI layer (import-boundary rule: `src/cli/` sits
 * above `src/emit/`, and even a type-only edge would invert the direction).
 */
export interface AgentsMdEmissionContext {
  /** The manifest driving substitution — detection summary plus the maturity dial. */
  manifest: SetupManifest;
  /** Live per-run detection decisions; only the monorepo layout is read here. */
  facts: {
    /** Workspace packages feeding the nested-copy plan; empty for single-package repos. */
    monorepoPackages: readonly PackageEntry[];
  };
  /**
   * Content root holding the charter template. Absent, the bundled corpus
   * root resolves — tests and tooling point this at a fixture corpus.
   */
  contentRoot?: string;
}

/** The rendered root charter with the measurements budget shaping reads. */
export interface RenderedAgentsMd {
  /** Emitted file content: frontmatter-free, fully substituted, one trailing newline. */
  content: string;
  /** UTF-8 byte length of `content` — the unit client size caps are stated in. */
  byteLength: number;
  /** Physical line count of `content` (`wc -l` semantics, matching the charter loader). */
  lineCount: number;
}

/** One planned nested copy of the rendered charter. */
export interface NestedAgentsMdTarget {
  /** Repo-relative path of the copy, posix-normalised. */
  outputPath: string;
  /** The copy's content — identical to the root render (verbatim re-target). */
  content: string;
}

/**
 * The full charter emission plan: the root render plus, per tool, the nested
 * monorepo copies for clients whose load model reads per-directory files.
 */
export interface AgentsMdPlan {
  root: RenderedAgentsMd;
  /**
   * Nested `AGENTS.md` targets for `tool` — one per workspace package, sorted
   * and deduplicated, repository root excluded, unusable package paths
   * skipped (all per the monorepo planner). Empty for every tool that does
   * not read per-directory files. Content is the root render verbatim: the
   * copy exists to give a package its own scope, not to vary the guidance.
   */
  nestedFor(tool: Tool): NestedAgentsMdTarget[];
}

/**
 * Render the root `AGENTS.md` (and expose its nested monorepo targets) from
 * the charter template plus the manifest.
 *
 * Substitution runs both token passes — repo facts (detection lists plus the
 * maturity dial) and verification gates — so the emitted file carries real
 * commands and real detections, never a template variable. The output ends
 * with exactly one trailing newline; beyond that normalisation the body is
 * the substituted template body byte-for-byte, in whatever line-ending form
 * the template's parser returned it.
 *
 * Propagates the charter loader's errors untouched: a missing template or one
 * over the always-on line budget is a corpus defect (`VALIDATION_ERROR`), and
 * truncating or partially rendering would hide it.
 */
export async function renderAgentsMd(ctx: AgentsMdEmissionContext): Promise<AgentsMdPlan> {
  const template = await readCharterTemplate(ctx.contentRoot);

  const substituted = substituteVerificationGateTokens(
    substituteRepoTokens(template.body, detectionContextFromManifest(ctx.manifest)),
    verificationGatesFromManifest(ctx.manifest),
  );
  const content = withSingleTrailingNewline(substituted);

  const root: RenderedAgentsMd = {
    content,
    byteLength: Buffer.byteLength(content, "utf8"),
    lineCount: countTerminatedLines(content),
  };

  // Captured once so the plan is a stable value: calling nestedFor later
  // (or twice) replans from the same package set the render saw.
  const packages = [...ctx.facts.monorepoPackages];

  return {
    root,
    nestedFor: (tool) =>
      planPerPackageOutputs(packages, tool, AGENTS_MD_FILE).map(({ outputPath }) => ({
        outputPath,
        content,
      })),
  };
}

/**
 * Verification-gate commands derivable from the persisted manifest.
 *
 * The manifest stores what detection found, not resolved commands, so the gates
 * are re-derived here by `src/detect/verificationGates.ts::verificationGatesFor`
 * — one resolver, so this render and every adapter that quotes a gate agree.
 * Its branch order, in full:
 *
 * 1. **No `detected` block** → the conventional npm defaults. Absence of the
 *    record is not a record of absence.
 * 2. **A ranked non-Node language** → that language's native row. Ranking is
 *    declared (`GATE_LANGUAGE_PRECEDENCE`), not the detection table's order.
 * 3. **Node evidence** — a ranked Node language, a persisted package manager,
 *    or a persisted `scripts` block → the script form for a script the repo
 *    declares, the DETECTED runner's binary when it does not.
 * 4. **No evidence for a gate** → that gate is absent and its charter row
 *    renders the `unknown` sentinel, naming no command beside it.
 *
 * Package-manager evidence IS read — it decides the run and exec prefixes — so
 * a pnpm or bun repo is never handed `npm run test`.
 */
export function verificationGatesFromManifest(manifest: SetupManifest): VerificationGateSet {
  return verificationGatesFor(manifest.detected);
}

/**
 * Exactly one trailing `\n`: runs of trailing newlines (LF or CRLF) collapse,
 * a missing terminator is added. A CRLF body keeps its interior line endings
 * as the template parser returned them — only the file's final terminator is
 * normalised, so no dangling `\r` survives at the end.
 */
function withSingleTrailingNewline(text: string): string {
  return `${text.replace(/(?:\r?\n)+$/, "")}\n`;
}

/**
 * Physical lines, `wc -l` style, for a body that already carries exactly one
 * trailing newline.
 *
 * {@link withSingleTrailingNewline} output is the only input this ever
 * receives, so the terminator is guaranteed and the count is just the number
 * of terminators. The empty-body and unterminated-tail cases the charter
 * loader's own counter carries are unreachable from here — spelling them out
 * anyway would add two branches no caller can produce an input for.
 */
function countTerminatedLines(text: string): number {
  return text.split(/\r?\n/).length - 1;
}
