/**
 * The core emission composer and the thin-adapter seam.
 *
 * The CORE emits once: the `AGENTS.md` charter (plus nested monorepo copies
 * where a client's load model needs them), the vendor-neutral
 * `.agents/skills/` projection, the 6-intent hooks infrastructure, and the MCP
 * substrate. ADAPTERS carry only per-client
 * residue — paths, dialects, scoping transforms, client flags — expressed as
 * {@link ResiduePlanner}s this module composes with the core plan. An adapter
 * that re-derives something the core already planned is the design defect
 * this seam exists to rule out.
 *
 * Ownership is the composer's second job. Shared core rows (root charter,
 * skills tree, policy document) are CO-OWNED by every
 * selected tool — one write, one ledger row per owner — so a shared file
 * survives deselection of any single tool (`src/manifest/ledger.ts`: a path
 * leaves the emission set only when every owner stops emitting it). Per-tool
 * core rows (hook script copies, nested charter copies) stay single-owner:
 * they exist only for their tool and should be reclaimed with it.
 *
 * Single-writer per path, enforced: rows are deduplicated by path with a
 * content-equality assertion — two planners emitting different bytes for one
 * path is a refused planner defect, never a silent last-write-wins. The one
 * sanctioned exception is the shared-path REPLACEMENT contract
 * (`AdapterOutput.replacesSharedPath`): a residue row may substitute its
 * content for a shared core row — owners unioned, still one write. No shipped
 * planner produces one today (the codex appendix moved to its own
 * `AGENTS.override.md` row); the branch stays as a generic contract.
 *
 * MCP placement follows the same split: {@link CoreEmissionPlan.mcpFor}
 * exposes each tool's dialect documents for its adapter to place, and the
 * composer itself places none. The `codex-toml` dialect is excluded from that
 * generic surface entirely — `.codex/config.toml` is a COMPOSED document the
 * codex adapter alone renders (MCP tables plus adapter tables), and handing
 * out a standalone MCP rendering of the same path would invite a double write.
 * The file itself is owned table by table: the engine's tables are merged
 * beside the owner's (`../manifest/codexConfigToml.ts`).
 *
 * The context and planner types here are engine-side structural twins of the
 * CLI layer's `EmissionContext`/`EmissionPlanner` (`src/cli/engine/emission.ts`):
 * the import-graph gate forbids engine modules importing the CLI layer, so
 * the shapes are restated — the CLI context satisfies this one by
 * construction, and a composed planner is assignable where the CLI seam
 * expects its own interface.
 *
 * Installed packs are the composer's third job (the live-emission invariant).
 * The context resolves them from `rootDir` + the manifest ledger
 * (`src/pack/projection.ts`): pack skills join the one `.agents/skills/`
 * projection, pack agents/rules/commands flow through the SAME per-tool
 * residue planners as corpus content — the composer hands residues a derived
 * context whose content roots include the installed packs and whose selection
 * admits their artifacts — and pack hook definitions join the wired user-hook
 * lane, so every class a pack may ship has a consuming path here. Projected
 * copies are ordinary adapter-owned rows, regenerated by sync and reclaimed
 * when the pack goes; the pack's own bytes under `.stamity/packs/` are never
 * planned (install-once).
 *
 * Planning is pure with respect to the working tree: corpus, pack, and
 * user-hook reads are reads of context; nothing here writes. Two plans over
 * identical input are byte-identical — stable path ordering, no clock, no
 * randomness.
 */

import { renderAgentsMd, AGENTS_MD_FILE, type AgentsMdPlan } from "./agentsMd.ts";
import { planHooksInfra, type CoreHooksPlan } from "./hooksInfra.ts";
import { isPluginOwned, sharedProjectionOwners } from "./ownership.ts";
import {
  projectSkills,
  SKILLS_PROJECTION_DIR,
  type ProjectedFile,
  type ProjectedSkillFile,
} from "./skillsProjection.ts";
import {
  buildContentIndex,
  contentRootsOf,
  describeInvocableNameClash,
  emittedIdFor,
  findInvocableNameClashes,
  layerRankOf,
  replacedClaimantOf,
  typeIdKey,
  type CatalogItem,
  type ContentIndex,
  type ContentRoots,
  type InvocableNameOwner,
} from "../content/catalog.ts";
import {
  NO_DEMOTED_RULES,
  SHARED_SKILLS_TREE_READERS,
  demotedRuleIds,
  ruleDeliveryInputOf,
} from "../content/ruleDelivery.ts";
import { buildSelectionAllowlist, classifySelection } from "../content/selection.ts";
import { readRuleDelivery } from "../manifest/manifest.ts";
import { effortDisclosures } from "../roster/modelLadder.ts";
import type { PackSuppliedServer } from "../mcp/catalog.ts";
import { planMcpEmissions, type McpDialect, type McpEmission } from "../mcp/emit.ts";
import {
  packHookDefinitions,
  resolveInstalledPackContent,
  selectionWithInstalledPacks,
  type ResolvedPackContent,
} from "../pack/projection.ts";
import { hasManagedBlock, wrapInManagedBlock } from "../merge/managedBlocks.ts";
import { pinnedCliCall, scopeRegistryArg } from "../shared/cliCall.ts";
import { cliCallContextOf, type CliCallContext } from "./substitution.ts";
import {
  outputOwners,
  type AdapterOutput,
  type ContentClass,
  type EmissionOwner,
  type EmissionPlan,
  type PackArtifactReach,
  type PackReach,
  type SourceRefusal,
} from "../types/content.ts";
import { TOOLS, type Tool } from "../types/core.ts";
import type { PackageEntry } from "../types/detect.ts";
import { EngineError } from "../types/errors.ts";
import { MANIFEST_FILE, type ImportDecision, type SetupManifest } from "../types/manifest.ts";
import { canHostManagedBlock, STATE_DIR } from "../types/markers.ts";

// ── Engine-side seam types (structural twins of the CLI seam) ────

/**
 * Everything a planner may read. The CLI layer's `EmissionContext` is
 * assignable to this shape unchanged; `contentRoot` is the extra optional
 * test seam production callers never pass (the bundled corpus resolves).
 */
export interface EmissionContext {
  /** Absolute repository root the outputs will be written under. */
  rootDir: string;
  /** The manifest driving selection — tools, content selection, dials. */
  manifest: SetupManifest;
  /** Engine version, for generator stamps inside emitted content and the pinned CLI call. */
  engineVersion: string;
  /**
   * The npm package the pinned CLI call names (`${STAMITY:CLI}` renders
   * `npx -y <packageName>@<engineVersion>`). Absent means the canonical
   * `@zomarit/stamity` (`DEFAULT_CLI_PACKAGE_NAME`); a fork that renamed its
   * package passes its own name so the rendered call runs the fork.
   */
  packageName?: string;
  /**
   * Whether that package has an npm channel. Absent means it does, and the
   * call renders `npx -y`; `false` — a fork that never publishes (private, no
   * `publishConfig.registry`) — renders `npx --no`, which runs a copy already
   * installed in the project and refuses to fetch one (`../shared/cliCall.ts`).
   */
  npmChannel?: boolean;
  /**
   * The registry that serves that package's scope — a `--registry` fork's
   * `publishConfig.registry` — which every pinned call names ahead of the spec
   * (`--@<scope>:registry=<url>`). Absent: the call names none.
   */
  npmRegistry?: string;
  /** Live per-run detection decisions. */
  facts: {
    /** Live monorepo package layout; empty for single-package repos. */
    monorepoPackages: readonly PackageEntry[];
    /**
     * Where the generated hook scripts live from the client's point of view;
     * absent means `HOOKS_GENERATED_DIR/<tool>`.
     */
    hookScriptsRoot?: string;
  };
  /**
   * Corpus root override; defaults to the package-bundled corpus. External
   * callers pass a string (or nothing — the CLI seam does not carry the
   * field at all); the widened {@link ContentRoots} form is the composer's
   * internal conduit, carrying installed-pack roots into the context residue
   * planners hand straight to `buildContentIndex`.
   */
  contentRoot?: string | ContentRoots;
}

/** Plans the files a run should emit. Implementations must not touch the filesystem. */
export interface EmissionPlanner {
  /** Stable identifier, for diagnostics only — callers never branch on it. */
  readonly id: string;
  /**
   * The rows alone: the narrow view, for callers with no reporting surface —
   * an adapter suite asserting what a residue emits, the pack-projection path
   * asking which files a pack lands. Implementations here define it as
   * `(await planWithWarnings(ctx)).outputs`, so the two views cannot disagree
   * about what a run emits and a caller cannot get rows from a different pass
   * than the findings it holds.
   */
  plan(ctx: EmissionContext): Promise<AdapterOutput[]>;
  /**
   * The whole planning result — rows plus what the pass found (see
   * {@link EmissionPlan}). Every consumer with a screen takes THIS one: `init`
   * and `sync` do, because the rows alone cannot express a hook that was
   * rejected and therefore has no row.
   */
  planWithWarnings(ctx: EmissionContext): Promise<EmissionPlan>;
}

// ── Core plan ────────────────────────────────────────────────────

/** The once-emitted core output every residue planner composes against. */
export interface CoreEmissionPlan {
  /** Root charter render plus per-tool nested monorepo targets. */
  agentsMd: AgentsMdPlan;
  /** The `.agents/skills/` projection, sorted by path. */
  skills: ProjectedFile[];
  /**
   * Per tool, the rule ids that tool does NOT carry as always-on rule text
   * because the delivery option moved them into {@link skills} — empty for
   * every tool under `ruleDelivery: "always-on"` (the default) and for every
   * tool the manifest does not select.
   *
   * Computed once here rather than per adapter, because the projection and the
   * adapters have to agree exactly: a rule an adapter skips but the projection
   * did not render is delivered nowhere, and one rendered but not skipped is
   * delivered twice (see `../content/ruleDelivery.ts`).
   */
  demotedRules: Readonly<Record<Tool, ReadonlySet<string>>>;
  /** Hook scripts, the shared policy document, and per-tool interchange rows. */
  hooks: CoreHooksPlan;
  /**
   * The MCP documents `tool`'s adapter places, in the tool's dialect order —
   * empty when the manifest selects no servers. `codex` always answers empty:
   * the `codex-toml` dialect is reserved for the codex residue composer,
   * which renders the engine's tables of `.codex/config.toml`, a file owned
   * table by table (see the module header).
   */
  mcpFor(tool: Tool): McpEmission[];
  /**
   * Every MCP server the installed packs supply, sorted by id — the same rows
   * {@link mcpFor} resolves against, exposed for the ONE adapter that renders
   * its own MCP tables (codex composes the engine's tables of `.codex/config.toml`). Any
   * other consumer takes {@link mcpFor}; this field is not a second selection
   * surface, and what a repo emits is still `manifest.mcp.servers`.
   */
  packMcpServers: readonly PackSuppliedServer[];
}

// ── Thin-adapter contract ────────────────────────────────────────

/**
 * Typed per-client capability declaration — the dialect facts an adapter
 * asserts about its platform, rendered into the generated capability matrix.
 * Every platform claim traces to a citation with an access date.
 */
export interface AdapterDialectFacts {
  tool: Tool;
  /** How the client scopes rules (e.g. `.mdc` globs, applyTo, nested files). */
  ruleShape: string;
  /**
   * Where hook config lands, or null when the client takes none v1. The hook
   * FAIL MODE (blocking vs advisory) is deliberately not restated here — its
   * source is `CLIENT_HOOK_GUARANTEES` (`src/hooks/model.ts`), which the
   * generated capability matrix renders alongside these facts.
   */
  hooksConfigPath: string | null;
  /** Whether the client reads the vendor-neutral `.agents/skills/` tree. */
  readsAgentsSkillsDir: boolean;
  /** The client's agent-definition format. */
  agentsFormat: string;
  /** The MCP config dialect the client consumes. */
  mcpDialect: McpDialect;
  /** Client entry file the adapter emits, or null when `AGENTS.md` is native. */
  entryFile: string | null;
  /** Named capability limits (budgets, caps), as declared value strings. */
  caps: { name: string; value: string }[];
  /** Platform citations backing the facts above. */
  citations: { url: string; accessDate: string }[];
}

/**
 * One tool's residue: the per-client rows the core does not own. Planners are
 * pure (no writes) and return rows already carrying ledger attribution; the
 * composer merges them with the core rows under the single-writer rules.
 */
/**
 * What one adapter's residue pass produced: its rows, and the findings no row
 * can carry.
 *
 * The second half is the reason this is an object rather than the array it used
 * to be. An adapter's most consequential per-client facts are precisely the
 * ones with no output to hang on — content the client's budget forced OUT of a
 * file, a shared path this client's emission replaced for every other selected
 * client — and the seam returned rows alone, so each was computed on every run
 * and discarded here. The core pass already had the channel
 * (`./hooksInfra.ts` → `CoreHooksPlan.warnings`, rendered by the init panel and
 * the sync report); this is the same channel, opened to the residue lane.
 */
export interface ResidueEmission {
  /** Rows this adapter owns. */
  outputs: AdapterOutput[];
  /**
   * Per-client disclosures, each already naming its own tool — the composer
   * merges them in canonical tool order and never re-labels them.
   */
  warnings?: readonly string[];
}

export interface ResiduePlanner {
  tool: Tool;
  facts: AdapterDialectFacts;
  planResidue(core: CoreEmissionPlan, ctx: EmissionContext): Promise<ResidueEmission>;
}

// ── Core artifact identities ─────────────────────────────────────

/** Ledger artifact id of every charter emission (root and nested copies). */
export const CHARTER_ARTIFACT_ID = "charter";

/** Ledger artifact id of the shared agent-tool policy document. */
export const POLICY_DOCUMENT_ARTIFACT_ID = "agent-tool-policies";

/** `stamity-session-start.mjs` → `stamity-session-start`: the script's ledger id. */
function hookScriptArtifactId(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1);
  const dot = base.lastIndexOf(".");
  return dot > 0 ? base.slice(0, dot) : base;
}

// ── Core aggregation ─────────────────────────────────────────────

/**
 * Aggregate the wave-0 core emitters into one plan: charter render, skills
 * projection, hooks infrastructure, and the per-tool MCP accessor. Reads
 * context only; the charter read honours the corpus half of `ctx.contentRoot`
 * when a caller pins one, and the skills read honours the corpus half AND the
 * repo's override tree — the whole of the layer, since a narrowed spec is what
 * used to make a user skill index as `origin: "user"` and emit as the shipped
 * body.
 *
 * Installed packs join the skills and hooks surfaces here: `packs` is the
 * resolved pack content (the composer resolves once and passes it down; a
 * direct caller may omit it and this function resolves from `ctx.rootDir` +
 * the manifest's ledger). Pack hook definitions are read through the
 * user-hook lane's ingress and handed to {@link planHooksInfra}, so they
 * reach every selected client's config. Pack skill rows merge into the one
 * `.agents/skills/` projection — sorted in among the corpus rows, carrying
 * their own ledger identity — so a pack skill is reachable exactly the way a
 * corpus skill is; a pack skill whose DIRECTORY name a corpus skill already
 * uses is refused by name here ({@link mergeSkillProjections}). A repo with no
 * installed packs resolves to an empty set and plans byte-identically to a
 * pack-unaware build.
 */
export async function buildCoreEmissionPlan(
  ctx: EmissionContext,
  packs?: ResolvedPackContent,
): Promise<CoreEmissionPlan> {
  const roots = contentRootsOf(ctx.contentRoot);
  const corpusRoot = roots.root;
  const contentRoot = corpusRoot === undefined ? {} : { contentRoot: corpusRoot };
  // The skills projection takes the corpus root AND the repo's override tree,
  // never the corpus half alone: narrowing here is what left a user `SKILL.md`
  // winning its id in the index and emitting the shipped body anyway.
  //
  // Pack roots join too, for a reason that has nothing to do with skills:
  // `buildContentIndex` discovers an overlay under EVERY class directory the
  // override tree holds, not only the class this call cares about, and
  // `applyOverlays` refuses any overlay whose base it cannot find in `byKey`.
  // Leaving pack roots out of this index — as an earlier revision did — made
  // an overlay on a pack agent, command or rule an orphan by this index's
  // lights alone, throwing here and blocking sync before the residue planners
  // (whose own indexes already carry both roots) ever got a chance to resolve
  // it correctly. An overlay on a pack SKILL is the one that never resolves:
  // see the end of this comment.
  //
  // Admitting pack roots to the LOOKUP does not admit pack skills to the
  // PROJECTION: `corpusSkills` below is filtered back down to non-pack rows
  // before it reaches `mergeSkillProjections`, so a pack skill still reaches
  // `.agents/skills/` exactly once, through `resolveInstalledPackContent` and
  // that merge. The pack-skill lane below never sees the override tree, only
  // this lookup does, so an overlay on a pack skill could not be reflected in
  // what gets projected — which is why it never resolves here at all:
  // `applyOverlays` (`../content/catalog.ts`) refuses it at the user stage and
  // skips and reports it at the fork stage, before this index is built.
  // The fork root rides along on the same terms as the override root: named
  // when the caller named it, and otherwise left to the walk, which pairs the
  // bundled fork layer with the bundled corpus it also resolves for itself.
  const skillsContentRootBase = {
    ...(corpusRoot === undefined ? {} : { root: corpusRoot }),
    ...(roots.forkRoot === undefined ? {} : { forkRoot: roots.forkRoot }),
    ...(roots.overrideRoot === undefined ? {} : { overrideRoot: roots.overrideRoot }),
  };
  // Pack resolution gates hooks planning (pack hook files are read through the
  // user-hook lane) the same way it now gates the skills-index lookup above —
  // installed-pack roots live on the RESOLVED set, not on `ctx.contentRoot`
  // (that spec is what the residue planners widen separately, in
  // `residueContext`; this function is handed `ctx` unwidened), so the lookup
  // has to wait on this promise rather than reading `roots.packRoots`, which
  // is always empty here. The charter read is the one that still does not.
  //
  // This is a real dependency EDGE, not a cosmetic reorder: `projectSkills` is
  // now serialized behind pack resolution (`packsPromise.then(...)` below)
  // wherever it used to start alongside the charter read in the same
  // `Promise.all`. A repo with no installed packs pays nothing extra —
  // `resolveInstalledPackContent` resolves to an empty pack set fast, and
  // `packRoots.length === 0` below then hands `projectSkills` the same
  // pack-free spec it always read — but a pack-having repo's skills read now
  // waits on the pack discovery walk finishing first, where it used to run
  // concurrently with it.
  const packsPromise =
    packs === undefined
      ? resolveInstalledPackContent(ctx.rootDir, ctx.manifest, corpusRoot)
      : Promise.resolve(packs);
  const [agentsMd, skillsPass, hooks, resolvedPacks] = await Promise.all([
    renderAgentsMd({
      manifest: ctx.manifest,
      engineVersion: ctx.engineVersion,
      ...(ctx.packageName === undefined ? {} : { packageName: ctx.packageName }),
      ...(ctx.npmChannel === undefined ? {} : { npmChannel: ctx.npmChannel }),
      ...(ctx.npmRegistry === undefined ? {} : { npmRegistry: ctx.npmRegistry }),
      facts: { monorepoPackages: ctx.facts.monorepoPackages },
      ...contentRoot,
    }),
    packsPromise.then(async (resolved) => {
      const skillsRoots = {
        ...skillsContentRootBase,
        ...(resolved.packRoots.length === 0 ? {} : { packRoots: resolved.packRoots }),
      };
      // The delivery answer is resolved BEFORE the projection, not beside it:
      // the projection renders a row for every rule the answer demotes, so the
      // two cannot be computed concurrently without one of them guessing.
      const delivery = await planRuleDelivery(ctx, skillsRoots);
      return {
        delivery,
        rows: await projectSkills(
          {
            manifest: ctx.manifest,
            engineVersion: ctx.engineVersion,
            ...(ctx.packageName === undefined ? {} : { packageName: ctx.packageName }),
            ...(ctx.npmChannel === undefined ? {} : { npmChannel: ctx.npmChannel }),
            ...(ctx.npmRegistry === undefined ? {} : { npmRegistry: ctx.npmRegistry }),
          },
          {
            contentRoot: skillsRoots,
            ruleItems: delivery.ruleItems,
            demotedRules: delivery.demotedRules,
          },
        ),
      };
    }),
    packsPromise.then(async (resolved) =>
      planHooksInfra({
        rootDir: ctx.rootDir,
        manifest: ctx.manifest,
        // The pinned CLI hint in the core scripts: the same package and
        // version the `${STAMITY:CLI}` token renders in every body.
        engineVersion: ctx.engineVersion,
        ...(ctx.packageName === undefined ? {} : { packageName: ctx.packageName }),
        ...(ctx.npmChannel === undefined ? {} : { npmChannel: ctx.npmChannel }),
        ...(ctx.npmRegistry === undefined ? {} : { npmRegistry: ctx.npmRegistry }),
        packHooks: await packHookDefinitions(resolved.packs, ctx.rootDir),
        // The agent-class half of the same seam: without these rows the
        // emitted policy document carries the shipped roster alone and the
        // generated guard answers NO_POLICY for every agent an install added.
        packAgents: resolved.agents,
        // The client's view of where those scripts will be READ from. A
        // repository emission leaves it absent and the planner composes the
        // repo-relative path it always did.
        ...(ctx.facts.hookScriptsRoot === undefined
          ? {}
          : { hookScriptsRoot: ctx.facts.hookScriptsRoot }),
        // Resolved HERE rather than in the hooks planner, which is handed a
        // manifest slice rather than the manifest: this function has the whole
        // of it, and `./ownership.ts` stays the one place the boundary is read.
        pluginOwnedHooks: TOOLS.filter((tool) => isPluginOwned(ctx.manifest, tool, "hooks")),
      }),
    ),
    packsPromise,
  ]);
  // `corpusSkills` now indexes pack roots too (above), so a pack skill with no
  // colliding id or directory is ADMITTED here alongside the corpus and
  // override ones — this filter is what keeps it from reaching emission
  // twice. `mergeSkillProjections` is the one place a pack skill projects,
  // and it still runs against `resolvedPacks`, whose own index never saw the
  // override tree — which is why an overlay on a pack skill never reaches this
  // lane: `applyOverlays` (`../content/catalog.ts`) refuses it at the override
  // stage, rather than resolving it here into a patch the pack lane ignores.
  // The filter is about pack SKILLS, not about pack origin as such: a demoted
  // rule supplied by an installed pack is projected by the lane above (the pack
  // skill lane knows nothing about rules), so filtering it out here would skip
  // it on its client AND deliver it nowhere.
  const skills = mergeSkillProjections(
    skillsPass.rows.filter((row) => row.artifactType !== "skill" || row.origin !== "pack"),
    resolvedPacks,
  );

  const serverIds = [...(ctx.manifest.mcp?.servers ?? [])];
  const protocolVersion = ctx.manifest.mcp?.protocolVersion;

  return {
    agentsMd,
    skills,
    demotedRules: skillsPass.delivery.demotedRules,
    hooks,
    packMcpServers: resolvedPacks.mcpServers,
    mcpFor: (tool) => {
      // Zero servers is a real answer: no document at all, for any tool —
      // never a present-but-empty config. codex is excluded by design (the
      // codex residue composer renders .codex/config.toml's engine tables,
      // which are merged table by table beside the owner's).
      if (serverIds.length === 0 || tool === "codex") return [];
      return planMcpEmissions(serverIds, [tool], {
        ...(protocolVersion === undefined ? {} : { protocolVersion }),
        // Pack supply is half the answer to "which ids resolve": `config mcp
        // add` accepts a pack-supplied id and records it in the selection, so
        // emission has to resolve it from the same seam. Dropping the rows
        // here made every selected pack server throw "nothing resolves them"
        // at sync and check — a false diagnostic whose only working remedy was
        // to deselect the server the operator had just chosen.
        packServers: resolvedPacks.mcpServers,
      });
    },
  };
}

/**
 * Which rules each selected client stops carrying always-on, and the rule items
 * the projection needs to render them as skills.
 *
 * Short-circuits on `always-on` — the default — so the pre-option build pays
 * nothing for the option: no second content walk, no rows, and a demotion
 * record that is empty for every tool.
 *
 * The rule set is filtered exactly the way each adapter filters its own
 * (`selectedItems` in the four adapters): catalog reachability, the manifest's
 * selection record, and the artifact's optional `tools:` restriction — the last
 * one per tool, since a rule restricted to another client is not a rule THIS
 * client was ever going to carry.
 */
async function planRuleDelivery(
  ctx: EmissionContext,
  contentRoot: ContentRoots,
): Promise<{
  ruleItems: readonly CatalogItem[];
  demotedRules: Readonly<Record<Tool, ReadonlySet<string>>>;
}> {
  const mode = readRuleDelivery(ctx.manifest);
  if (mode === "always-on") return { ruleItems: [], demotedRules: NO_DEMOTED_RULES };

  const index = await buildContentIndex(contentRoot);
  const allowlist = buildSelectionAllowlist(ctx.manifest.selection);
  const ruleItems = index.items.filter(
    (item) =>
      item.type === "rule" &&
      index.byKey.get(typeIdKey(item.type, item.id)) === item &&
      classifySelection(item, allowlist) !== "drop",
  );

  const selected = new Set<Tool>(ctx.manifest.tools);
  const demotedRules = Object.fromEntries(
    TOOLS.map((tool) => [
      tool,
      selected.has(tool)
        ? demotedRuleIds(
            tool,
            ruleItems
              .filter((item) => item.tools === undefined || item.tools.includes(tool))
              .map(ruleDeliveryInputOf),
            mode,
            SHARED_SKILLS_TREE_READERS,
          )
        : new Set<string>(),
    ]),
  ) as Record<Tool, ReadonlySet<string>>;

  return { ruleItems, demotedRules };
}

/**
 * The corpus skill rows merged with the installed packs', sorted by path — and
 * the one place a pack's skill DIRECTORY name can collide with a corpus
 * skill's.
 *
 * The catalog already refuses a pack that claims an existing skill ID
 * (`../content/catalog.ts`, "Packs must not shadow existing content"). A
 * DIRECTORY clash is the case that rule does not cover: two skills with
 * different ids may still be authored under one directory name, and both
 * projections target `<SKILLS_PROJECTION_DIR>/<dir>/…`, so the two row sets
 * overlap path for path.
 *
 * Detecting it HERE is what makes the diagnosis nameable. Left to the
 * composer's content-equality dedup, the same state surfaced as "two planners
 * emitted different content for … (owners: claude, cursor, copilot, codex)" —
 * four tools that had nothing to do with it, no mention of the pack that
 * introduced the directory, and two remedies (make the emissions byte-identical,
 * flag one with `replacesSharedPath`) an operator cannot act on and an adapter
 * author should not. The refusal below names the pack, the corpus skill it
 * collides with, and the two things the operator can actually do. The
 * cross-class form of the same clash — a command and a skill of one name — is
 * one this function cannot see (a command's folder is a residue row), and is
 * refused before planning starts, for the same reason, by
 * {@link refuseInvocableNameClashes}.
 *
 * Byte-identical content is refused too, and on purpose: the clash is the
 * shared directory, not the bytes. Two skills merged into one tree by
 * coincidence of content would still interleave their `references/` subtrees
 * under one name, and the ledger would attribute the result to whichever
 * artifact claimed the path first.
 *
 * `corpusSkills` is not corpus-only despite the name: it is `projectSkills`'
 * output over the corpus root, the repo's override tree AND the installed
 * pack roots (`buildCoreEmissionPlan`'s `skillsContentRoot`), filtered back
 * down to non-pack rows before it reaches this function — the pack roots ride
 * along so that index can resolve an overlay addressed at a pack agent,
 * command or rule (see `buildCoreEmissionPlan`'s comment), not so a pack skill
 * projects from here. An overlay on a pack skill never resolves in that index:
 * `applyOverlays` (`../content/catalog.ts`) refuses it at the user stage and
 * skips and reports it at the fork stage. A row that survives the filter can still be
 * `origin: "user"`, and because the lookup DID see the pack roots, an override
 * claiming a pack skill's id or directory was already resolved (shadow or
 * collision) inside that index — but the PROJECTION check below is still what
 * catches it, because `resolvedPacks.skillRows` (this function's other input)
 * comes from a lane that never saw the override tree at all and would emit
 * the pack skill's own rows regardless. Two shapes, caught before the generic
 * directory-collision throw above ever fires on them, and both arriving as ONE
 * path collision because of the projection's directory rule
 * (`../emit/skillsProjection.ts` → `projectSkills`: a customizing skill that
 * took a shipped id projects into the REPLACED skill's directory):
 *
 * - **Same directory, different id.** An override skill's DIRECTORY is also a
 *   pack skill's directory. Falling through to the directory-collision throw
 *   would name the corpus skill and tell the operator to rename or remove the
 *   PACK — wrong on both counts, since the row sharing that directory is the
 *   override, not a corpus skill, and the pack was never the thing that moved.
 * - **Same id.** An override claims a pack skill's catalog id, from whatever
 *   directory its author filed it under. The index resolved the override over
 *   the pack skill (the pack roots are in the lookup, so this is a shadow),
 *   the projection therefore laid it down in the pack skill's directory, and
 *   the pack lane — which never saw the override tree — projects the pack
 *   skill there too. Before the directory rule this shape collided on no
 *   path at all and both bodies projected silently under one catalog id; now
 *   it is the same collision the first shape is, told apart by the id.
 *
 * Pack-skill overrides are unsupported today. Both shapes refuse naming the
 * OVERRIDE file as the thing to remove or rename; removing the pack is the
 * stated alternative, exactly as the corpus-vs-pack throw below offers for its
 * own case.
 *
 * A FORK skill (`origin: "fork"`, the package's `fork/skills/<dir>/SKILL.md`)
 * takes the override's side of every one of these rules: it projects through
 * this lane like a corpus or override skill, and a fork skill claiming a pack
 * skill's id or directory is refused by the same two shapes, naming the fork
 * file. The fork is one layer below the override tree and one above the packs
 * (`../content/catalog.ts`), and the pack lane never saw either, so the seam
 * is the same one.
 */
function mergeSkillProjections(
  corpusSkills: readonly ProjectedSkillFile[],
  packs: ResolvedPackContent,
): ProjectedFile[] {
  refuseOverrideDirectoryClash(corpusSkills);
  const corpusByPath = new Map(corpusSkills.map((row) => [row.path, row]));
  for (const row of packs.skillRows) {
    const corpusRow = corpusByPath.get(row.path);
    if (corpusRow === undefined) continue;
    const packId = packSupplierOf(packs.items, row.artifactId);
    if (isCustomizingRow(corpusRow)) {
      const overridePath = customizingSkillFilePath(corpusRow);
      const noun = customizingNounOf(corpusRow);
      const shape =
        corpusRow.artifactId === row.artifactId
          ? `takes the catalog id ("${row.artifactId}") of ${
              packId === undefined ? "an installed pack" : `installed pack "${packId}"`
            }'s skill, and so projects into that skill's directory`
          : `shares its directory with the pack skill "${row.artifactId}"'s`;
      throw new EngineError(
        `Pack-skill overrides are unsupported today: the ${noun} at "${overridePath}" ${shape} ` +
          `(both would project to the client). Remove or rename ${overridePath}, or remove ` +
          `the pack (\`clean --pack ${packId ?? "<pack-id>"}\`).`,
        { code: "VALIDATION_ERROR" },
      );
    }
    throw new EngineError(
      `${packId === undefined ? "An installed pack" : `Installed pack "${packId}"`} supplies ` +
        `skill "${row.artifactId}" under a directory the corpus skill ` +
        `"${corpusRow.artifactId}" already projects into: both emit "${corpusRow.path}". One ` +
        `${SKILLS_PROJECTION_DIR} directory holds one skill — projecting both would write each ` +
        `skill's files over the other's. Rename the skill's directory inside the pack, or remove ` +
        `the pack (\`clean --pack ${packId ?? "<pack-id>"}\`).`,
      { code: "VALIDATION_ERROR" },
    );
  }
  return [...corpusSkills, ...packs.skillRows].toSorted((a, b) =>
    a.path < b.path ? -1 : a.path > b.path ? 1 : 0,
  );
}

/** `.agents/skills/<dir>/SKILL.md` → `<dir>`: the directory one skill projects into. */
function projectionDirOf(path: string): string {
  return path.slice(`${SKILLS_PROJECTION_DIR}/`.length).split("/")[0] ?? "";
}

/**
 * The clash the guards above do not cover, because no pack is involved in it:
 * an OVERRIDE skill's directory is also a CORPUS skill's directory, under two
 * different catalog ids.
 *
 * A skill projects into `<SKILLS_PROJECTION_DIR>/<dir>/`, and for a skill that
 * replaced nothing `<dir>` is the authored directory name
 * (`../emit/skillsProjection.ts`), not the id. So an override authored at
 * `.stamity/overrides/skills/st-verify/SKILL.md` that declares `id: st-probe`
 * is a NEW artifact — it shadows nothing, the catalog indexes both — and both
 * project into `.agents/skills/st-verify/`, file for file. (A skill that DID
 * take a shipped id projects into the replaced skill's directory, whose
 * previous occupant left the index with the id, so a replacement never lands
 * here.) The catalog records the id/directory mismatch as a collision and
 * `validate` reports it; emission reads no such field, so `sync` fell through
 * to the composer's content-equality refusal, which names four adapters, the
 * shared path and neither the override nor the skill it collided with.
 *
 * Refused with the override named as the thing to move, for the same reason
 * the pack shapes above name the override: it is the file the operator wrote
 * and the only one they can rename without touching shipped content.
 *
 * The fork layer sits between the two: a fork skill's directory clashing with
 * a corpus skill's is refused naming the fork file, and an override's directory
 * clashing with a fork skill's is refused naming the override — in each pair
 * the HIGHER layer is the one that moves, because the lower one is shipped
 * content from where that author stands.
 */
function refuseOverrideDirectoryClash(corpusSkills: readonly ProjectedSkillFile[]): void {
  // Only a lower-layer row can be the thing a customizing row collides WITH:
  // two shipped skills sharing a directory under two ids cannot be authored,
  // because there the directory is the id. Keep the lowest layer's row per
  // directory, so the refusal names the most shipped thing in the way.
  const lowestByDir = new Map<string, ProjectedSkillFile>();
  for (const row of corpusSkills) {
    const dir = projectionDirOf(row.path);
    const held = lowestByDir.get(dir);
    if (held === undefined || layerRankOf(row) < layerRankOf(held)) lowestByDir.set(dir, row);
  }

  for (const row of corpusSkills) {
    if (!isCustomizingRow(row)) continue;
    const other = lowestByDir.get(projectionDirOf(row.path));
    if (
      other === undefined ||
      layerRankOf(other) >= layerRankOf(row) ||
      other.artifactId === row.artifactId
    ) {
      continue;
    }
    const overridePath = customizingSkillFilePath(row);
    const noun = customizingNounOf(row);
    throw new EngineError(
      `The ${noun} at "${overridePath}" declares id "${row.artifactId}" but sits in a ` +
        `directory the skill "${other.artifactId}" already projects into: both emit ` +
        `"${other.path}". One ${SKILLS_PROJECTION_DIR} directory holds one skill — projecting ` +
        `both would write each skill's files over the other's. Rename the ${noun}'s directory ` +
        `to match its own id ("${row.artifactId}"), or change the id to override ` +
        `"${other.artifactId}" outright.`,
      { code: "VALIDATION_ERROR" },
    );
  }
}

/**
 * The two layers that customize shipped content and are named as the thing to
 * move in every refusal above: the repo's override tree and the package's
 * fork layer. A corpus row, a pack row and an unstamped row are all "shipped"
 * from where those authors stand.
 */
function isCustomizingRow(row: ProjectedFile): boolean {
  return row.origin === "user" || row.origin === "fork";
}

/** How a refusal calls the customizing row it names: the file the author can move. */
function customizingNounOf(row: ProjectedFile): string {
  return row.origin === "fork" ? "fork skill" : "override";
}

/**
 * The pack that supplied a skill id, or `undefined` when the resolved content
 * set carries no item for it — true of a set assembled by hand rather than
 * walked, which is the only way `skillRows` and `items` can disagree.
 */
function packSupplierOf(items: readonly CatalogItem[], skillId: string): string | undefined {
  return items.find((item) => item.type === "skill" && item.id === skillId)?.provenance?.pack;
}

/**
 * The source file an `origin: "user"` or `origin: "fork"` skill row was
 * rendered from, read off the row's own `artifactPath` rather than off its
 * emitted path: a replacement projects under the REPLACED skill's directory
 * (`skillsProjection.ts` → `projectSkills`), so the emitted directory no longer
 * says where the author's file is. A fork row names the package-relative
 * `fork/skills/<dir>/SKILL.md`, the spelling a fork author edits; an override
 * row names the repo-relative override tree.
 */
function customizingSkillFilePath(row: ProjectedSkillFile): string {
  return row.origin === "fork"
    ? `fork/${row.artifactPath}`
    : `${STATE_DIR}/overrides/${row.artifactPath}`;
}

/**
 * Refuse a content set in which artifacts of two classes would install under
 * one invocable name — a command and a skill (or a rule delivered as a skill)
 * whose folders are both `st-<x>`.
 *
 * The catalog keys identity by class, so nothing per class sees it: on Cursor
 * and Codex the command's touchpoint folder and the skill's folder are one
 * path, which surfaced only as the composer's "two planners emitted different
 * content" with four adapters named and no owner; on Claude no path is shared
 * and the skill silently hides the command. `add` refuses such a pack before
 * writing it, but a repository can already hold one — a pack installed by an
 * engine without that check, an override, a fork artifact — and `sync`,
 * `check`, `init` and `plugin setup` all plan through here.
 *
 * `index` is the residue context's full walk: the corpus with its fork and
 * override layers applied, plus the installed packs. A replacing skill is named
 * through the claimant it replaced, because it lands in that claimant's folder
 * (`./skillsProjection.ts` → `projectSkills`) — leaving `replacedOf` out lets an
 * override that took a core skill's id slip past beside a pack command of that
 * name. Every clash is listed in one refusal, then one remedy per owner that
 * can move: the corpus cannot, so a core owner adds none, and a name only core
 * owners claim is named as a defect of the package instead.
 *
 * `cli` pins every command the refusal names to this run's package and
 * version (`npx -y <package>@<version> <verb>`), the form `check`'s
 * `pack-reach` row prints for the same `clean --pack` step: a bare `stamity`
 * resolves only where a global install put it on PATH, which the documented
 * `npx` setup never does.
 */
function refuseInvocableNameClashes(index: ContentIndex, cli: CliCallContext): void {
  const clashes = findInvocableNameClashes(index.items, {
    replacedOf: (item) => replacedClaimantOf(index, item),
  });
  if (clashes.length === 0) return;
  const remedies = [
    ...new Set(clashes.flatMap((clash) => clash.owners.flatMap((owner) => remedyOf(owner, cli)))),
  ];
  // A name every owner of which is shipped core content has no remedy here: no
  // file in this repository can move. Said so by name, rather than left under a
  // "Move one owner" heading that offers nothing for it.
  const coreOnly = clashes
    .filter((clash) => clash.owners.every((owner) => remedyOf(owner, cli).length === 0))
    .map((clash) => clash.name);
  // The fixed text has to fit every clash it can carry: a skill against a rule
  // delivered as a skill involves no command, so nothing is hidden on Claude.
  const hidesCommand = clashes.some((clash) =>
    clash.owners.some((owner) => owner.kind === "command"),
  );
  throw new EngineError(
    [
      `${clashes.length} name(s) are claimed by artifacts of more than one class, so nothing ` +
        `was planned:`,
      ...clashes.map((clash) => `  ${describeInvocableNameClash(clash)}`),
      ...(remedies.length === 0
        ? []
        : ["Move one owner of each name:", ...remedies.map((remedy) => `  - ${remedy}`)]),
      ...(coreOnly.length === 0
        ? []
        : [
            `${coreOnly.join(", ")}: every owner is core content shipped with this package, so ` +
              `nothing in this repository can move — a defect of the package, to report to its ` +
              `maintainers`,
          ]),
    ].join("\n"),
    {
      code: "VALIDATION_ERROR",
      why: hidesCommand
        ? "every artifact listed installs into the one folder its name gives it, so on Cursor " +
          "and Codex they overwrite each other's files, and on Claude a skill hides the command " +
          "of its name"
        : "every artifact listed would share the one skill folder its name gives it wherever " +
          "it is delivered as a skill — a rule is, on a client that demotes it — so there " +
          "they overwrite each other's files",
      // `sync`, `check`, `init` and `plugin setup` all plan through here, so the
      // step names the command that stopped rather than assuming it was sync.
      next:
        remedies.length === 0
          ? "report the clash to the package's maintainers; no file in this repository can " +
            "resolve it"
          : "apply one remedy per name listed above, then re-run the command that stopped " +
            `here (\`${remedyCall(cli, "sync")}\`, \`${remedyCall(cli, "check")}\`, ` +
            `\`${remedyCall(cli, "init")}\` or \`${remedyCall(cli, "plugin setup")}\`)`,
    },
  );
}

/**
 * The remedy for one owner of a clashing name, or none for a core owner. A
 * pack's remedy has a step by hand between `clean --pack` and `sync`:
 * `clean --pack` removes a pack's client copies only as bytes the engine
 * renders from the installed pack, and a pack this refusal names cannot be
 * planned, so its copies are kept, named and disowned. Left on disk, they
 * collide with the copies the re-added pack's `sync` writes.
 */
function remedyOf(owner: InvocableNameOwner, cli: CliCallContext): string[] {
  switch (owner.layer) {
    case "pack": {
      const packId = owner.packId ?? "<pack-id>";
      return [
        `pack "${packId}": run \`${remedyCall(cli, `clean --pack ${packId}`)}\`, then delete by ` +
          `hand each client copy it keeps and names (a clashing pack cannot prove them), then ` +
          `\`${remedyCall(cli, "sync")}\`, then ` +
          `\`${remedyCall(cli, `add ${packId}`)}\` once the pack ships distinct names, then ` +
          `\`${remedyCall(cli, "sync")}\``,
      ];
    }
    case "user":
      return [`the override at ${owner.path}: rename or remove ${owner.path}`];
    case "fork":
      return [
        `the fork-layer file at ${owner.path}: rename or remove it in the fork's source, then ` +
          `publish the package again — a defect in the package's fork layer, not in this ` +
          `repository`,
      ];
    default:
      return [];
  }
}

/**
 * One command a refusal names, pinned as `pinnedCliCall` spells it. A refusal
 * prints on an error path, so a context that cannot be pinned (a version that
 * is not semver-shaped) keeps the unpinned `npx <package> <verb>` rather than
 * replacing the operator's diagnosis with a rendering failure — the fallback
 * the CLI's own `packageCommand` takes.
 */
function remedyCall(cli: CliCallContext, verb: string): string {
  try {
    return pinnedCliCall(cli.packageName, cli.version, verb, cli);
  } catch {
    // The fallback carries the scope's registry too. A registry the call
    // refuses to write is never rendered; the fallback then fails closed to
    // `--no`, which fetches nothing.
    let words = [cli.npmChannel === false ? "--no" : ""];
    try {
      words.push(scopeRegistryArg(cli.packageName, cli.registry));
    } catch {
      words = ["--no"];
    }
    return ["npx", ...words, cli.packageName, verb].filter((word) => word !== "").join(" ");
  }
}

// ── Composition ──────────────────────────────────────────────────

/** One path being assembled: content plus its owner list (one per adapter). */
interface PendingRow {
  path: string;
  content: string;
  owners: EmissionOwner[];
  /** Carried from the residue row that set it; see `AdapterOutput.sourceRefusal`. */
  sourceRefusal?: SourceRefusal;
}

/**
 * Compose the core plan with the registered residue planners into the one
 * `EmissionPlanner` the CLI seam consumes.
 *
 * Per `ctx.manifest.tools` (normalized to canonical {@link TOOLS} order):
 * shared core rows are co-owned by every selected tool; per-tool hook scripts
 * and nested charter copies are owned by their tool; each selected tool's
 * residue rows merge in under the single-writer rules (content-equality
 * dedup, shared-path replacement). A selected tool with no registered residue
 * planner gets core-only emission — a legal state the production registry
 * makes unreachable. Output rows are sorted by path (codepoint order), so two
 * plans over identical input are byte-identical.
 *
 * The planner id is stable and diagnostic-only: it names the registered
 * residue set, never varies with the context, and no caller branches on it.
 *
 * The core pass's findings leave with the rows. `CoreHooksPlan.warnings`
 * (`./hooksInfra.ts`) is built here and returned on {@link EmissionPlan}, which
 * is the whole of what makes a rejected hook, an empty pack-agent grant or an
 * over-cap policy document reachable by a report. This composer used to return
 * the rows alone, and the channel died at exactly this line: the diagnosis was
 * computed on every run and had nowhere to go, so the failures it names reached
 * an operator only as behaviour (the hook that never fires).
 */
export function composeEmissionPlanner(
  residues: Partial<Record<Tool, ResiduePlanner>>,
): EmissionPlanner {
  const registered = TOOLS.filter((tool) => residues[tool] !== undefined);

  const planWithWarnings = async (ctx: EmissionContext): Promise<EmissionPlan> => {
    const packs = await resolveInstalledPackContent(
      ctx.rootDir,
      ctx.manifest,
      contentRootsOf(ctx.contentRoot).root,
    );
    const residueCtx = residueContext(ctx, packs);
    // Before any row exists: a cross-class name clash is refused with its
    // owners named, rather than reaching the single-writer check below as two
    // planners writing one path (or, on Claude, as nothing at all).
    refuseInvocableNameClashes(await buildContentIndex(residueCtx.contentRoot), cliCallContextOf(ctx));
    const core = await buildCoreEmissionPlan(ctx, packs);
    const tools = TOOLS.filter((tool) => ctx.manifest.tools.includes(tool));

    const rows = new Map<string, PendingRow>();
    const sharedPaths = new Set<string>();
    const replacedPaths = new Set<string>();

    const sharedOwners = (artifactId: string, artifactType: EmissionOwner["artifactType"]) =>
      tools.map((tool) => ({ adapter: tool, artifactId, artifactType }));

    /**
     * The selected clients that actually READ {@link SKILLS_PROJECTION_DIR},
     * off their own dialect facts.
     *
     * The projection used to be emitted for any non-empty selection, so a
     * claude-only repo received the whole `.agents/skills/` tree — every skill,
     * byte-identical to the native `.claude/skills/` copy the same run writes —
     * for a client whose own facts row says it does not read that directory.
     * On a claude+cursor repo the cost changes shape rather than disappearing:
     * cursor discovers each skill in both trees.
     *
     * They are also the OWNERS of those rows, which is what makes the tree
     * reclaimable: deselect every reader and the last owner drops, so the sweep
     * removes a projection nothing reads any more.
     *
     * The test is `!== false`, not `=== true`: only a REGISTERED adapter that
     * positively declares it does not read the tree is excluded. A tool with no
     * residue planner registered (the core-rows-only composition) has no facts
     * to consult, and in that mode the neutral projection is the only skills
     * surface the run produces at all — so an absent declaration keeps it.
     */
    const projectionReaders = tools.filter(
      (tool) => residues[tool]?.facts.readsAgentsSkillsDir !== false,
    );

    // Shared core rows — co-owned by ALL selected tools. With no tool
    // selected there is nothing to own, so nothing is emitted at all.
    if (tools.length > 0) {
      addRow(
        rows,
        AGENTS_MD_FILE,
        core.agentsMd.root.content,
        sharedOwners(CHARTER_ARTIFACT_ID, "infra"),
      );
      // Ownership of the shared tree is narrowed once, off the manifest: a
      // reader whose plugin CARRIES `skill` receives those skills from its own
      // plugin root, so it is no longer an owner here and the tree is emitted
      // while any reader remains (`./ownership.ts`). With no `plugin` field
      // this is `projectionReaders` itself and nothing about the plan moves.
      //
      // A PACK skill is the documented exception, and it is decided per row:
      // pack content is installed into THIS repository, no plugin ships it,
      // and dropping its owners would leave an installed pack's skills
      // reachable by no client at all. So a pack row keeps every reader.
      const projectionOwners = sharedProjectionOwners(ctx.manifest, projectionReaders);
      for (const file of core.skills) {
        const owners = file.origin === "pack" ? projectionReaders : projectionOwners;
        if (owners.length === 0) continue;
        addRow(
          rows,
          file.path,
          file.content,
          owners.map((tool) => ({
            adapter: tool,
            artifactId: file.artifactId,
            artifactType: file.artifactType,
          })),
        );
      }
      const policy = core.hooks.policyDocument;
      if (policy.owners.length > 0) {
        addRow(
          rows,
          policy.path,
          policy.content,
          policy.owners.map((tool) => ({
            adapter: tool,
            artifactId: POLICY_DOCUMENT_ARTIFACT_ID,
            artifactType: "infra" as const,
          })),
        );
      }
      for (const path of rows.keys()) sharedPaths.add(path);
    }

    // Per-tool core rows — owned singly, reclaimed with their tool.
    for (const script of core.hooks.scripts) {
      addRow(rows, script.path, script.content, [
        {
          adapter: script.tool,
          artifactId: hookScriptArtifactId(script.path),
          artifactType: "infra",
        },
      ]);
    }
    for (const tool of tools) {
      for (const nested of core.agentsMd.nestedFor(tool)) {
        addRow(rows, nested.outputPath, nested.content, [
          { adapter: tool, artifactId: CHARTER_ARTIFACT_ID, artifactType: "infra" },
        ]);
      }
    }

    // Residues — planned in parallel (independent, read-only), merged in
    // canonical tool order so the composed plan and any refused defect are
    // deterministic regardless of completion order. They receive the
    // pack-aware context, so installed pack content flows through each
    // adapter's own dialect emission (per-tool rules, agents, commands).
    const settled = await Promise.allSettled(
      tools.map(
        (tool) =>
          residues[tool]?.planResidue(core, residueCtx) ??
          Promise.resolve<ResidueEmission>({ outputs: [] }),
      ),
    );
    // Merged in the same canonical tool order as the rows, and appended AFTER
    // the core findings, so one run's diagnosis reads in the order it was
    // produced rather than in completion order.
    const residueWarnings: string[] = [];
    for (const [index, tool] of tools.entries()) {
      const outcome = settled[index]!;
      if (outcome.status === "rejected") {
        const reason: unknown = outcome.reason;
        throw new EngineError(
          `The "${tool}" residue planner failed while planning its per-client output: ` +
            `${reason instanceof Error ? reason.message : String(reason)}. No files were ` +
            `written. Fix the adapter defect (or deselect the tool) and re-run.`,
          { code: "ADAPTER_ERROR", cause: reason },
        );
      }
      for (const output of outcome.value.outputs) {
        mergeResidueRow(rows, sharedPaths, replacedPaths, tool, output);
      }
      residueWarnings.push(...(outcome.value.warnings ?? []));
    }

    // Last, over the finished row set: the user's pre-existing config files
    // outrank every planner's opinion about the paths they sit on.
    applyImportDecisions(rows, importDecisionsOf(ctx.manifest), ctx.engineVersion);

    const outputs = [...rows.values()]
      .toSorted((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
      .map((row) => {
        const output: AdapterOutput = {
          path: row.path,
          content: row.content,
          owner: row.owners[0]!,
        };
        // Key left absent (not `undefined`-valued) on single-owner rows, so
        // co-owner-unaware consumers see the pre-seam shape byte-for-byte.
        if (row.owners.length > 1) output.coOwners = row.owners.slice(1);
        if (row.sourceRefusal !== undefined) output.sourceRefusal = row.sourceRefusal;
        return output;
      });

    // Copied, not aliased: the plan is handed to a caller that may keep it for
    // the length of a run, and the core plan object is this pass's own.
    //
    // The effort disclosures join the hooks plan's findings rather than the
    // residues': they are a fact about the MANIFEST read against the client
    // scales, identical for every planner, so deriving them once here keeps
    // four adapters from each reporting the same narrowing.
    return {
      outputs,
      warnings: [...core.hooks.warnings, ...effortDisclosures(ctx.manifest), ...residueWarnings],
      // Judged against the same selection and the same ownership boundary the
      // rows above were built under, so `check` reads the reach of THIS plan.
      packReach: await packReachOf(ctx, packs, tools),
    };
  };

  return {
    id: `core+residue[${registered.join(",")}]`,
    plan: async (ctx) => (await planWithWarnings(ctx)).outputs,
    planWithWarnings,
  };
}

// ── Pack reach ───────────────────────────────────────────────────

/**
 * Per installed pack, which selected clients each artifact it ships reaches,
 * and why it misses the ones it does not — the plan's `packReach`, which
 * `check`'s `pack-reach` row reads (`../cli/commands/check.ts`). A pack none of
 * whose artifacts reaches a client is installed and does nothing; in
 * plugin-backed mode that is the ordinary fate of a command-only pack on
 * Claude, Cursor and Copilot, and nothing else on any surface said so.
 *
 * Read off the two filters every adapter applies to pack content, not off the
 * planned rows: the artifact's own `tools:` list, and the ownership boundary
 * ({@link isPluginOwned}, the one place a plugin's classes are decided). The
 * rows cannot answer it — a pack rule reaches Codex as text inside the
 * down-conversion appendix, a composite document no per-rule row owns, so a
 * join on row owners would call a delivered rule dropped. Per class:
 *
 * - **skill** — every selected client: pack skills are the documented
 *   exception to plugin ownership (above, `projectionOwners`) and are
 *   projected verbatim, `tools:` unread, like the pack skill lane projects them;
 * - **agent, rule, command** — every client its `tools:` list admits whose
 *   plugin does not carry the class;
 * - **hooks** — one artifact per pack hook file the hook lane accepted, reaching
 *   every client whose hooks this repository wires: a client whose plugin
 *   carries `hooks` takes its configuration from the plugin root, which is
 *   the hooks planner's "not wired" warning. A file every row of which was
 *   rejected is not an artifact here; that planner's warning names it. Read
 *   per pack, because the core pass reads all packs' hooks as one lane;
 * - **mcp-server** — every selected client when `manifest.mcp.servers` selects
 *   it (no plugin carries `mcp`; Claude, Cursor and Copilot place it through
 *   {@link CoreEmissionPlan.mcpFor}, Codex composes it into its own config),
 *   and none, dropped as `not selected`, when it does not: installing a pack
 *   makes its servers selectable, never selected (`../mcp/emit.ts` →
 *   `McpRenderOptions.packServers`), so it reaches nothing until
 *   `config mcp add <id>`.
 */
async function packReachOf(
  ctx: EmissionContext,
  packs: ResolvedPackContent,
  tools: readonly Tool[],
): Promise<PackReach[]> {
  const selectedServers = new Set(ctx.manifest.mcp?.servers ?? []);
  return Promise.all(
    packs.packs.map(async (pack) => {
      const hookFiles = pack.classesPresent.includes("hooks")
        ? (await packHookDefinitions([pack], ctx.rootDir)).hooks.map((hook) =>
            hook.sourceFile.replaceAll("\\", "/"),
          )
        : [];
      return {
        packId: pack.id,
        artifacts: [
          ...packs.items
            .filter((item) => item.provenance?.pack === pack.id)
            .map((item) => contentReachOf(ctx.manifest, tools, item)),
          ...[...new Set(hookFiles)]
            .toSorted()
            .map((file) => classReachOf(ctx.manifest, tools, "hooks", file)),
          ...packs.mcpServers
            .filter((server) => server.sourcePackId === pack.id)
            .map(
              (server): PackArtifactReach =>
                selectedServers.has(server.id)
                  ? { kind: "mcp-server", id: server.id, reachedBy: [...tools], dropped: [] }
                  : {
                      kind: "mcp-server",
                      id: server.id,
                      reachedBy: [],
                      dropped: [{ reason: "not selected" }],
                    },
            ),
        ],
      };
    }),
  );
}

/** One pack content item's reach: see {@link packReachOf}. */
function contentReachOf(
  manifest: SetupManifest,
  tools: readonly Tool[],
  item: CatalogItem,
): PackArtifactReach {
  const id = emittedIdFor(item);
  if (item.type === "skill") return { kind: "skill", id, reachedBy: [...tools], dropped: [] };
  const declared = item.tools;
  if (declared !== undefined && !tools.some((tool) => declared.includes(tool))) {
    return {
      kind: item.type,
      id,
      reachedBy: [],
      dropped: [{ reason: "declares no selected client", declared: [...declared] }],
    };
  }
  const targeted =
    declared === undefined ? tools : tools.filter((tool) => declared.includes(tool));
  return classReachOf(manifest, targeted, item.type, id);
}

/** Split `targeted` into the clients that reach a `cls` artifact and the ones whose plugin owns it. */
function classReachOf(
  manifest: SetupManifest,
  targeted: readonly Tool[],
  cls: Exclude<ContentClass, "skill"> | "hooks",
  id: string,
): PackArtifactReach {
  return {
    kind: cls,
    id,
    reachedBy: targeted.filter((tool) => !isPluginOwned(manifest, tool, cls)),
    dropped: targeted
      .filter((tool) => isPluginOwned(manifest, tool, cls))
      .map((tool) => ({ reason: "plugin-owned" as const, tool, cls })),
  };
}

/**
 * The context residue planners receive: `ctx` itself for a repo with no pack
 * content (identity preserved, so a no-packs plan is byte-identical to a
 * pack-unaware build), or a derived context whose `contentRoot` carries the
 * installed-pack roots and whose manifest selection also admits the pack
 * artifacts (installed = selected).
 *
 * Widening, never narrowing: the spec is rebuilt part by part, so every part
 * the caller passed in survives the rebuild. The repo's own override tree
 * (`ContentRoots.overrideRoot`) is the one that used to be dropped, and the
 * cost of dropping it was invisible — the customization layer did not error in
 * a pack-having repo, it silently stopped arriving, and where an override held
 * a shipped id the SHIPPED body emitted under it. A part omitted here is a
 * content layer that appears or disappears with unrelated state, which is why
 * the rebuild carries all four — the package's fork root
 * (`ContentRoots.forkRoot`) included — rather than the two the pack wiring
 * needed.
 *
 * The derivation is what projects pack content through the per-tool residue
 * surfaces WITHOUT an adapter edit: every adapter already walks
 * `buildContentIndex(ctx.contentRoot)` and filters through the manifest
 * selection, so widening those two inputs is the whole wiring. The rows an
 * adapter emits for pack items carry that adapter as owner — ordinary
 * ADAPTER-owned ledger rows sourced from pack content — which is exactly what
 * makes sync regenerate them and a removed pack's projections reclaimable:
 * the pack's rows vanish from the ledger, the next plan omits the
 * projections, and the reclaim diff sweeps the copies. Pack SOURCE bytes
 * under `.stamity/packs/` are never planned here at all (install-once).
 */
function residueContext(ctx: EmissionContext, packs: ResolvedPackContent): EmissionContext {
  if (packs.items.length === 0) return ctx;
  const spec = contentRootsOf(ctx.contentRoot);
  return {
    ...ctx,
    contentRoot: {
      ...(spec.root === undefined ? {} : { root: spec.root }),
      packRoots: [...spec.packRoots, ...packs.packRoots],
      ...(spec.forkRoot === undefined ? {} : { forkRoot: spec.forkRoot }),
      ...(spec.overrideRoot === undefined ? {} : { overrideRoot: spec.overrideRoot }),
    },
    manifest: selectionWithInstalledPacks(ctx.manifest, packs.items),
  };
}

/**
 * The persisted existing-config decisions, as a list.
 *
 * Read straight off the manifest, with no reshaping: `SetupManifest.importChoice`
 * (`../types/manifest.ts`) holds ONE record per pre-existing instruction file,
 * which is what detection actually returns — a repo carrying `CLAUDE.md` and
 * `.github/copilot-instructions.md` yields two, pinned by
 * `test/cli/commands/initPlan.test.ts`. An absent field is a greenfield repo
 * and means no decisions, not an empty one to invent.
 *
 * The identity is the point. This function used to wrap a single persisted
 * record into a 0-or-1 element array, so {@link applyImportDecisions} — which
 * has always looped — could never receive more than one decision, and every
 * detected path past the first was planned as an ordinary engine-owned row the
 * operator was never asked about. The schema, the init ask, and the manifest
 * composition all carry the list now, so the wrap has nothing left to do.
 */
function importDecisionsOf(manifest: SetupManifest): readonly ImportDecision[] {
  return manifest.importChoice ?? [];
}

/**
 * Execute the persisted existing-config decisions against the
 * planned rows — every decision, not the first one. This is the one place the
 * three modes become behaviour, and it runs over the FINISHED row set so a
 * residue planner cannot reintroduce a path after its decision was applied.
 *
 * - **skip** — the row is dropped. No bytes, and (because the ledger records
 *   only emitted rows) no ownership claim, so `sync` and `check` see a file the
 *   engine does not emit rather than an unowned collision they refuse on.
 * - **supplement** — a block-less row is wrapped in a managed block, which
 *   routes the write through the merge lane: the block lands above the user's
 *   file and every other byte is preserved verbatim. A row that already
 *   carries a block (the `CLAUDE.md` bridge) is already supplementing and is
 *   left alone, which is also what makes a second pass over the same decision
 *   set a no-op.
 * - **replace** — bytes are unchanged here; replacement is a WRITE-lane
 *   decision (force over the user's file behind a verified `.bak`), taken by
 *   `cli/commands/init/apply.ts` on the same manifest record.
 *
 * A decision naming a path this plan does not emit is inert — the file was an
 * instruction file for a client whose adapter emits nothing there, and the
 * honest answer is to leave it alone, which is what emitting nothing does.
 * Decisions are applied in list order; each names its own path, so the order
 * is observable only when two of them name the same one, where last wins.
 */
function applyImportDecisions(
  rows: Map<string, PendingRow>,
  decisions: readonly ImportDecision[],
  engineVersion: string,
): void {
  for (const decision of decisions) applyImportDecision(rows, decision, engineVersion);
}

/** One decision against the row holding its path, if this plan emits that path. */
function applyImportDecision(
  rows: Map<string, PendingRow>,
  decision: ImportDecision,
  engineVersion: string,
): void {
  const row = rows.get(decision.path);
  if (row === undefined) return;
  if (decision.mode === "skip") {
    rows.delete(decision.path);
    return;
  }
  if (decision.mode !== "supplement") return;
  // The markers module's "plain JSON is never wrapped" is an absolute about a
  // format, and this is the site that could break it: the path comes from a
  // persisted record, the row set holds JSON documents (`.claude/settings.json`,
  // the MCP configs), and `getMarkersForPath` answers HTML for an unmapped
  // extension rather than refusing. Wrapping one produced a settings file the
  // client could no longer parse — a supplement that disabled the tool it was
  // supplementing.
  if (!canHostManagedBlock(decision.path)) {
    throw new EngineError(
      `The recorded import decision for "${decision.path}" is "supplement", but that file has no ` +
        `comment syntax to carry a managed block — the markers would make it unparseable for the ` +
        `client that reads it. Record "skip" (leave the file alone) or "replace" (write over it ` +
        `behind a verified .bak) for this path in ${STATE_DIR}/${MANIFEST_FILE}, or remove the ` +
        `decision so the file is emitted normally.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  if (!hasManagedBlock(row.content, decision.path)) {
    row.content = wrapInManagedBlock(row.content, decision.path, engineVersion);
  }
}

/**
 * Insert one row, or merge it into the row already holding its path: equal
 * content unions owners (deduplicated by adapter — ledger row identity is the
 * `(adapter, path)` pair); different content is a refused planner defect that
 * names the path and every claimant, because a silent overwrite here would
 * ship one adapter's bytes under another adapter's ledger row.
 */
function addRow(
  rows: Map<string, PendingRow>,
  path: string,
  content: string,
  owners: readonly EmissionOwner[],
): void {
  const existing = rows.get(path);
  if (existing === undefined) {
    rows.set(path, { path, content, owners: dedupeOwners([], owners) });
    return;
  }
  if (existing.content !== content) {
    const claimants = [...existing.owners, ...owners].map((owner) => owner.adapter).join(", ");
    throw new EngineError(
      `Two planners emitted different content for "${path}" (owners: ${claimants}). ` +
        `One path has one writer: make the emissions byte-identical, or flag the ` +
        `overriding row with replacesSharedPath for a shared core path.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  existing.owners = dedupeOwners(existing.owners, owners);
}

/** Merge one residue output, honouring the shared-path replacement contract. */
function mergeResidueRow(
  rows: Map<string, PendingRow>,
  sharedPaths: ReadonlySet<string>,
  replacedPaths: Set<string>,
  tool: Tool,
  output: AdapterOutput,
): void {
  const owners = outputOwners(output);
  if (output.replacesSharedPath !== true) {
    addRow(rows, output.path, output.content, owners);
    // A refusal travels with its row: dropping it here would hand the writers a
    // row they cannot tell apart from an ordinary one.
    if (output.sourceRefusal !== undefined) rows.get(output.path)!.sourceRefusal = output.sourceRefusal;
    return;
  }
  if (!sharedPaths.has(output.path)) {
    throw new EngineError(
      `The "${tool}" residue planner flagged "${output.path}" with replacesSharedPath, but ` +
        `the core plan does not emit that path as a shared row. Replacement substitutes a ` +
        `co-owned core emission (e.g. the root ${AGENTS_MD_FILE}); emit any other path as a ` +
        `plain residue row instead.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  if (replacedPaths.has(output.path)) {
    throw new EngineError(
      `Two residue planners replaced the shared path "${output.path}" (second: "${tool}"). ` +
        `A shared row takes at most one replacement per plan — one path, one writer.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  replacedPaths.add(output.path);
  const target = rows.get(output.path)!;
  target.content = output.content;
  target.owners = dedupeOwners(target.owners, owners);
}

/** `base` extended with `extra`, first triple per adapter winning, as a fresh array. */
function dedupeOwners(
  base: readonly EmissionOwner[],
  extra: readonly EmissionOwner[],
): EmissionOwner[] {
  const merged: EmissionOwner[] = [];
  const seen = new Set<Tool>();
  for (const owner of [...base, ...extra]) {
    if (seen.has(owner.adapter)) continue;
    seen.add(owner.adapter);
    merged.push({
      adapter: owner.adapter,
      artifactId: owner.artifactId,
      artifactType: owner.artifactType,
    });
  }
  return merged;
}
