/**
 * The core emission composer and the thin-adapter seam.
 *
 * The CORE emits once: the `AGENTS.md` charter (plus nested monorepo copies
 * where a client's load model needs them), the vendor-neutral
 * `.agents/skills/` projection, the 6-intent hooks infrastructure, and the MCP
 * substrate. ADAPTERS carry only per-client
 * residue — paths, dialects, scoping transforms, client flags — expressed as
 * {@link ResiduePlanner}s this module composes with the core plan. An adapter
 * that re-derives something the core already planned is the design defect
 * this seam exists to rule out.
 *
 * Ownership is the composer's second job. Shared core rows (root charter,
 * skills tree, policy document) are CO-OWNED by every
 * selected tool — one write, one ledger row per owner — so a shared file
 * survives deselection of any single tool (`src/manifest/ledger.ts`: a path
 * leaves the emission set only when every owner stops emitting it). Per-tool
 * core rows (hook script copies, nested charter copies) stay single-owner:
 * they exist only for their tool and should be reclaimed with it.
 *
 * Single-writer per path, enforced: rows are deduplicated by path with a
 * content-equality assertion — two planners emitting different bytes for one
 * path is a refused planner defect, never a silent last-write-wins. The one
 * sanctioned exception is the shared-path REPLACEMENT contract
 * (`AdapterOutput.replacesSharedPath`): a residue row may substitute its
 * content for a shared core row — owners unioned, still one write — which is
 * how the codex adapter delivers a root-appendix charter body without a
 * second writer on `AGENTS.md`.
 *
 * MCP placement follows the same split: {@link CoreEmissionPlan.mcpFor}
 * exposes each tool's dialect documents for its adapter to place, and the
 * composer itself places none. The `codex-toml` dialect is excluded from that
 * generic surface entirely — `.codex/config.toml` is a COMPOSED document the
 * codex adapter owns whole (MCP tables plus adapter tables), and handing out
 * a standalone MCP rendering of the same path would invite a double write.
 *
 * The context and planner types here are engine-side structural twins of the
 * CLI layer's `EmissionContext`/`EmissionPlanner` (`src/cli/engine/emission.ts`):
 * the import-graph gate forbids engine modules importing the CLI layer, so
 * the shapes are restated — the CLI context satisfies this one by
 * construction, and a composed planner is assignable where the CLI seam
 * expects its own interface.
 *
 * Installed packs are the composer's third job (the live-emission invariant).
 * The context resolves them from `rootDir` + the manifest ledger
 * (`src/pack/projection.ts`): pack skills join the one `.agents/skills/`
 * projection, pack agents/rules/commands flow through the SAME per-tool
 * residue planners as corpus content — the composer hands residues a derived
 * context whose content roots include the installed packs and whose selection
 * admits their artifacts — and pack hook definitions join the wired user-hook
 * lane, so every class a pack may ship has a consuming path here. Projected
 * copies are ordinary adapter-owned rows, regenerated by sync and reclaimed
 * when the pack goes; the pack's own bytes under `.stamity/packs/` are never
 * planned (install-once).
 *
 * Planning is pure with respect to the working tree: corpus, pack, and
 * user-hook reads are reads of context; nothing here writes. Two plans over
 * identical input are byte-identical — stable path ordering, no clock, no
 * randomness.
 */

import { renderAgentsMd, AGENTS_MD_FILE, type AgentsMdPlan } from "./agentsMd.ts";
import { planHooksInfra, type CoreHooksPlan } from "./hooksInfra.ts";
import { projectSkills, SKILLS_PROJECTION_DIR, type ProjectedFile } from "./skillsProjection.ts";
import { contentRootsOf, type CatalogItem, type ContentRoots } from "../content/catalog.ts";
import type { PackSuppliedServer } from "../mcp/catalog.ts";
import { planMcpEmissions, type McpDialect, type McpEmission } from "../mcp/emit.ts";
import {
  packHookDefinitions,
  resolveInstalledPackContent,
  selectionWithInstalledPacks,
  type ResolvedPackContent,
} from "../pack/projection.ts";
import { hasManagedBlock, wrapInManagedBlock } from "../merge/managedBlocks.ts";
import {
  outputOwners,
  type AdapterOutput,
  type EmissionOwner,
  type EmissionPlan,
} from "../types/content.ts";
import { TOOLS, type Tool } from "../types/core.ts";
import type { PackageEntry } from "../types/detect.ts";
import { EngineError } from "../types/errors.ts";
import { MANIFEST_FILE, type ImportDecision, type SetupManifest } from "../types/manifest.ts";
import { canHostManagedBlock, STATE_DIR } from "../types/markers.ts";

// ── Engine-side seam types (structural twins of the CLI seam) ────

/**
 * Everything a planner may read. The CLI layer's `EmissionContext` is
 * assignable to this shape unchanged; `contentRoot` is the extra optional
 * test seam production callers never pass (the bundled corpus resolves).
 */
export interface EmissionContext {
  /** Absolute repository root the outputs will be written under. */
  rootDir: string;
  /** The manifest driving selection — tools, content selection, dials. */
  manifest: SetupManifest;
  /** Engine version, for generator stamps inside emitted content. */
  engineVersion: string;
  /** Live per-run detection decisions. */
  facts: {
    /** True when the repo had no agentic setup before this run. */
    greenfield: boolean;
    /** Live monorepo package layout; empty for single-package repos. */
    monorepoPackages: readonly PackageEntry[];
  };
  /**
   * Corpus root override; defaults to the package-bundled corpus. External
   * callers pass a string (or nothing — the CLI seam does not carry the
   * field at all); the widened {@link ContentRoots} form is the composer's
   * internal conduit, carrying installed-pack roots into the context residue
   * planners hand straight to `buildContentIndex`.
   */
  contentRoot?: string | ContentRoots;
}

/** Plans the files a run should emit. Implementations must not touch the filesystem. */
export interface EmissionPlanner {
  /** Stable identifier, for diagnostics only — callers never branch on it. */
  readonly id: string;
  /**
   * The rows alone: the narrow view, for callers with no reporting surface —
   * an adapter suite asserting what a residue emits, the pack-projection path
   * asking which files a pack lands. Implementations here define it as
   * `(await planWithWarnings(ctx)).outputs`, so the two views cannot disagree
   * about what a run emits and a caller cannot get rows from a different pass
   * than the findings it holds.
   */
  plan(ctx: EmissionContext): Promise<AdapterOutput[]>;
  /**
   * The whole planning result — rows plus what the pass found (see
   * {@link EmissionPlan}). Every consumer with a screen takes THIS one: `init`
   * and `sync` do, because the rows alone cannot express a hook that was
   * rejected and therefore has no row.
   */
  planWithWarnings(ctx: EmissionContext): Promise<EmissionPlan>;
}

// ── Core plan ────────────────────────────────────────────────────

/** The once-emitted core output every residue planner composes against. */
export interface CoreEmissionPlan {
  /** Root charter render plus per-tool nested monorepo targets. */
  agentsMd: AgentsMdPlan;
  /** The `.agents/skills/` projection, sorted by path. */
  skills: ProjectedFile[];
  /** Hook scripts, the shared policy document, and per-tool interchange rows. */
  hooks: CoreHooksPlan;
  /**
   * The MCP documents `tool`'s adapter places, in the tool's dialect order —
   * empty when the manifest selects no servers. `codex` always answers empty:
   * the `codex-toml` dialect is reserved for the codex residue composer,
   * which owns `.codex/config.toml` whole (see the module header).
   */
  mcpFor(tool: Tool): McpEmission[];
  /**
   * Every MCP server the installed packs supply, sorted by id — the same rows
   * {@link mcpFor} resolves against, exposed for the ONE adapter that renders
   * its own MCP document (codex composes `.codex/config.toml` whole). Any
   * other consumer takes {@link mcpFor}; this field is not a second selection
   * surface, and what a repo emits is still `manifest.mcp.servers`.
   */
  packMcpServers: readonly PackSuppliedServer[];
}

// ── Thin-adapter contract ────────────────────────────────────────

/**
 * Typed per-client capability declaration — the dialect facts an adapter
 * asserts about its platform, rendered into the generated capability matrix.
 * Every platform claim traces to a citation with an access date.
 */
export interface AdapterDialectFacts {
  tool: Tool;
  /** How the client scopes rules (e.g. `.mdc` globs, applyTo, nested files). */
  ruleShape: string;
  /**
   * Where hook config lands, or null when the client takes none v1. The hook
   * FAIL MODE (blocking vs advisory) is deliberately not restated here — its
   * source is `CLIENT_HOOK_GUARANTEES` (`src/hooks/model.ts`), which the
   * generated capability matrix renders alongside these facts.
   */
  hooksConfigPath: string | null;
  /** Whether the client reads the vendor-neutral `.agents/skills/` tree. */
  readsAgentsSkillsDir: boolean;
  /** The client's agent-definition format. */
  agentsFormat: string;
  /** The MCP config dialect the client consumes. */
  mcpDialect: McpDialect;
  /** Client entry file the adapter emits, or null when `AGENTS.md` is native. */
  entryFile: string | null;
  /** Named capability limits (budgets, caps), as declared value strings. */
  caps: { name: string; value: string }[];
  /** Platform citations backing the facts above. */
  citations: { url: string; accessDate: string }[];
}

/**
 * One tool's residue: the per-client rows the core does not own. Planners are
 * pure (no writes) and return rows already carrying ledger attribution; the
 * composer merges them with the core rows under the single-writer rules.
 */
/**
 * What one adapter's residue pass produced: its rows, and the findings no row
 * can carry.
 *
 * The second half is the reason this is an object rather than the array it used
 * to be. An adapter's most consequential per-client facts are precisely the
 * ones with no output to hang on — content the client's budget forced OUT of a
 * file, a shared path this client's emission replaced for every other selected
 * client — and the seam returned rows alone, so each was computed on every run
 * and discarded here. The core pass already had the channel
 * (`./hooksInfra.ts` → `CoreHooksPlan.warnings`, rendered by the init panel and
 * the sync report); this is the same channel, opened to the residue lane.
 */
export interface ResidueEmission {
  /** Rows this adapter owns. */
  outputs: AdapterOutput[];
  /**
   * Per-client disclosures, each already naming its own tool — the composer
   * merges them in canonical tool order and never re-labels them.
   */
  warnings?: readonly string[];
}

export interface ResiduePlanner {
  tool: Tool;
  facts: AdapterDialectFacts;
  planResidue(core: CoreEmissionPlan, ctx: EmissionContext): Promise<ResidueEmission>;
}

// ── Core artifact identities ─────────────────────────────────────

/** Ledger artifact id of every charter emission (root and nested copies). */
export const CHARTER_ARTIFACT_ID = "charter";

/** Ledger artifact id of the shared agent-tool policy document. */
export const POLICY_DOCUMENT_ARTIFACT_ID = "agent-tool-policies";

/** `stamity-session-start.mjs` → `stamity-session-start`: the script's ledger id. */
function hookScriptArtifactId(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1);
  const dot = base.lastIndexOf(".");
  return dot > 0 ? base.slice(0, dot) : base;
}

// ── Core aggregation ─────────────────────────────────────────────

/**
 * Aggregate the wave-0 core emitters into one plan: charter render, skills
 * projection, hooks infrastructure, and the per-tool MCP accessor. Reads
 * context only; the charter and skills reads honour the corpus half of
 * `ctx.contentRoot` when a caller pins one.
 *
 * Installed packs join the skills and hooks surfaces here: `packs` is the
 * resolved pack content (the composer resolves once and passes it down; a
 * direct caller may omit it and this function resolves from `ctx.rootDir` +
 * the manifest's ledger). Pack hook definitions are read through the
 * user-hook lane's ingress and handed to {@link planHooksInfra}, so they
 * reach every selected client's config. Pack skill rows merge into the one
 * `.agents/skills/` projection — sorted in among the corpus rows, carrying
 * their own ledger identity — so a pack skill is reachable exactly the way a
 * corpus skill is; a pack skill whose DIRECTORY name a corpus skill already
 * uses is refused by name here ({@link mergeSkillProjections}). A repo with no
 * installed packs resolves to an empty set and plans byte-identically to a
 * pack-unaware build.
 */
export async function buildCoreEmissionPlan(
  ctx: EmissionContext,
  packs?: ResolvedPackContent,
): Promise<CoreEmissionPlan> {
  const corpusRoot = contentRootsOf(ctx.contentRoot).root;
  const contentRoot = corpusRoot === undefined ? {} : { contentRoot: corpusRoot };
  // Pack resolution gates hooks planning (pack hook files are read through the
  // user-hook lane) and nothing else, so it is a dependency EDGE inside the
  // parallel fan — the charter and skills reads never wait on it.
  const packsPromise =
    packs === undefined
      ? resolveInstalledPackContent(ctx.rootDir, ctx.manifest, corpusRoot)
      : Promise.resolve(packs);
  const [agentsMd, corpusSkills, hooks, resolvedPacks] = await Promise.all([
    renderAgentsMd({
      manifest: ctx.manifest,
      facts: { monorepoPackages: ctx.facts.monorepoPackages },
      ...contentRoot,
    }),
    projectSkills({ manifest: ctx.manifest, engineVersion: ctx.engineVersion }, contentRoot),
    packsPromise.then(async (resolved) =>
      planHooksInfra({
        rootDir: ctx.rootDir,
        manifest: ctx.manifest,
        packHooks: await packHookDefinitions(resolved.packs, ctx.rootDir),
        // The agent-class half of the same seam: without these rows the
        // emitted policy document carries the shipped roster alone and the
        // generated guard answers NO_POLICY for every agent an install added.
        packAgents: resolved.agents,
      }),
    ),
    packsPromise,
  ]);
  const skills = mergeSkillProjections(corpusSkills, resolvedPacks);

  const serverIds = [...(ctx.manifest.mcp?.servers ?? [])];
  const protocolVersion = ctx.manifest.mcp?.protocolVersion;

  return {
    agentsMd,
    skills,
    hooks,
    packMcpServers: resolvedPacks.mcpServers,
    mcpFor: (tool) => {
      // Zero servers is a real answer: no document at all, for any tool —
      // never a present-but-empty config. codex is excluded by design (the
      // codex residue composer owns .codex/config.toml whole).
      if (serverIds.length === 0 || tool === "codex") return [];
      return planMcpEmissions(serverIds, [tool], {
        ...(protocolVersion === undefined ? {} : { protocolVersion }),
        // Pack supply is half the answer to "which ids resolve": `config mcp
        // add` accepts a pack-supplied id and records it in the selection, so
        // emission has to resolve it from the same seam. Dropping the rows
        // here made every selected pack server throw "nothing resolves them"
        // at sync and check — a false diagnostic whose only working remedy was
        // to deselect the server the operator had just chosen.
        packServers: resolvedPacks.mcpServers,
      });
    },
  };
}

/**
 * The corpus skill rows merged with the installed packs', sorted by path — and
 * the one place a pack's skill DIRECTORY name can collide with a corpus
 * skill's.
 *
 * The catalog already refuses a pack that claims an existing skill ID
 * (`../content/catalog.ts`, "Packs must not shadow existing content"). A
 * DIRECTORY clash is the case that rule does not cover: two skills with
 * different ids may still be authored under one directory name, and both
 * projections target `<SKILLS_PROJECTION_DIR>/<dir>/…`, so the two row sets
 * overlap path for path.
 *
 * Detecting it HERE is what makes the diagnosis nameable. Left to the
 * composer's content-equality dedup, the same state surfaced as "two planners
 * emitted different content for … (owners: claude, cursor, copilot, codex)" —
 * four tools that had nothing to do with it, no mention of the pack that
 * introduced the directory, and two remedies (make the emissions byte-identical,
 * flag one with `replacesSharedPath`) an operator cannot act on and an adapter
 * author should not. The refusal below names the pack, the corpus skill it
 * collides with, and the two things the operator can actually do.
 *
 * Byte-identical content is refused too, and on purpose: the clash is the
 * shared directory, not the bytes. Two skills merged into one tree by
 * coincidence of content would still interleave their `references/` subtrees
 * under one name, and the ledger would attribute the result to whichever
 * artifact claimed the path first.
 */
function mergeSkillProjections(
  corpusSkills: readonly ProjectedFile[],
  packs: ResolvedPackContent,
): ProjectedFile[] {
  const corpusByPath = new Map(corpusSkills.map((row) => [row.path, row]));
  for (const row of packs.skillRows) {
    const corpusRow = corpusByPath.get(row.path);
    if (corpusRow === undefined) continue;
    const packId = packSupplierOf(packs.items, row.artifactId);
    throw new EngineError(
      `${packId === undefined ? "An installed pack" : `Installed pack "${packId}"`} supplies ` +
        `skill "${row.artifactId}" under a directory the corpus skill ` +
        `"${corpusRow.artifactId}" already projects into: both emit "${corpusRow.path}". One ` +
        `${SKILLS_PROJECTION_DIR} directory holds one skill — projecting both would write each ` +
        `skill's files over the other's. Rename the skill's directory inside the pack, or remove ` +
        `the pack (\`clean --pack ${packId ?? "<pack-id>"}\`).`,
      { code: "VALIDATION_ERROR" },
    );
  }
  return [...corpusSkills, ...packs.skillRows].toSorted((a, b) =>
    a.path < b.path ? -1 : a.path > b.path ? 1 : 0,
  );
}

/**
 * The pack that supplied a skill id, or `undefined` when the resolved content
 * set carries no item for it — true of a set assembled by hand rather than
 * walked, which is the only way `skillRows` and `items` can disagree.
 */
function packSupplierOf(items: readonly CatalogItem[], skillId: string): string | undefined {
  return items.find((item) => item.type === "skill" && item.id === skillId)?.provenance?.pack;
}

// ── Composition ──────────────────────────────────────────────────

/** One path being assembled: content plus its owner list (one per adapter). */
interface PendingRow {
  path: string;
  content: string;
  owners: EmissionOwner[];
}

/**
 * Compose the core plan with the registered residue planners into the one
 * `EmissionPlanner` the CLI seam consumes.
 *
 * Per `ctx.manifest.tools` (normalized to canonical {@link TOOLS} order):
 * shared core rows are co-owned by every selected tool; per-tool hook scripts
 * and nested charter copies are owned by their tool; each selected tool's
 * residue rows merge in under the single-writer rules (content-equality
 * dedup, shared-path replacement). A selected tool with no registered residue
 * planner gets core-only emission — a legal state the production registry
 * makes unreachable. Output rows are sorted by path (codepoint order), so two
 * plans over identical input are byte-identical.
 *
 * The planner id is stable and diagnostic-only: it names the registered
 * residue set, never varies with the context, and no caller branches on it.
 *
 * The core pass's findings leave with the rows. `CoreHooksPlan.warnings`
 * (`./hooksInfra.ts`) is built here and returned on {@link EmissionPlan}, which
 * is the whole of what makes a rejected hook, an empty pack-agent grant or an
 * over-cap policy document reachable by a report. This composer used to return
 * the rows alone, and the channel died at exactly this line: the diagnosis was
 * computed on every run and had nowhere to go, so the failures it names reached
 * an operator only as behaviour (the hook that never fires).
 */
export function composeEmissionPlanner(
  residues: Partial<Record<Tool, ResiduePlanner>>,
): EmissionPlanner {
  const registered = TOOLS.filter((tool) => residues[tool] !== undefined);

  const planWithWarnings = async (ctx: EmissionContext): Promise<EmissionPlan> => {
    const packs = await resolveInstalledPackContent(
      ctx.rootDir,
      ctx.manifest,
      contentRootsOf(ctx.contentRoot).root,
    );
    const core = await buildCoreEmissionPlan(ctx, packs);
    const residueCtx = residueContext(ctx, packs);
    const tools = TOOLS.filter((tool) => ctx.manifest.tools.includes(tool));

    const rows = new Map<string, PendingRow>();
    const sharedPaths = new Set<string>();
    const replacedPaths = new Set<string>();

    const sharedOwners = (artifactId: string, artifactType: EmissionOwner["artifactType"]) =>
      tools.map((tool) => ({ adapter: tool, artifactId, artifactType }));

    /**
     * The selected clients that actually READ {@link SKILLS_PROJECTION_DIR},
     * off their own dialect facts.
     *
     * The projection used to be emitted for any non-empty selection, so a
     * claude-only repo received the whole `.agents/skills/` tree — every skill,
     * byte-identical to the native `.claude/skills/` copy the same run writes —
     * for a client whose own facts row says it does not read that directory.
     * On a claude+cursor repo the cost changes shape rather than disappearing:
     * cursor discovers each skill in both trees.
     *
     * They are also the OWNERS of those rows, which is what makes the tree
     * reclaimable: deselect every reader and the last owner drops, so the sweep
     * removes a projection nothing reads any more.
     *
     * The test is `!== false`, not `=== true`: only a REGISTERED adapter that
     * positively declares it does not read the tree is excluded. A tool with no
     * residue planner registered (the core-rows-only composition) has no facts
     * to consult, and in that mode the neutral projection is the only skills
     * surface the run produces at all — so an absent declaration keeps it.
     */
    const projectionReaders = tools.filter(
      (tool) => residues[tool]?.facts.readsAgentsSkillsDir !== false,
    );

    // Shared core rows — co-owned by ALL selected tools. With no tool
    // selected there is nothing to own, so nothing is emitted at all.
    if (tools.length > 0) {
      addRow(
        rows,
        AGENTS_MD_FILE,
        core.agentsMd.root.content,
        sharedOwners(CHARTER_ARTIFACT_ID, "infra"),
      );
      for (const file of core.skills) {
        if (projectionReaders.length === 0) break;
        addRow(
          rows,
          file.path,
          file.content,
          projectionReaders.map((tool) => ({
            adapter: tool,
            artifactId: file.artifactId,
            artifactType: file.artifactType,
          })),
        );
      }
      const policy = core.hooks.policyDocument;
      if (policy.owners.length > 0) {
        addRow(
          rows,
          policy.path,
          policy.content,
          policy.owners.map((tool) => ({
            adapter: tool,
            artifactId: POLICY_DOCUMENT_ARTIFACT_ID,
            artifactType: "infra" as const,
          })),
        );
      }
      for (const path of rows.keys()) sharedPaths.add(path);
    }

    // Per-tool core rows — owned singly, reclaimed with their tool.
    for (const script of core.hooks.scripts) {
      addRow(rows, script.path, script.content, [
        {
          adapter: script.tool,
          artifactId: hookScriptArtifactId(script.path),
          artifactType: "infra",
        },
      ]);
    }
    for (const tool of tools) {
      for (const nested of core.agentsMd.nestedFor(tool)) {
        addRow(rows, nested.outputPath, nested.content, [
          { adapter: tool, artifactId: CHARTER_ARTIFACT_ID, artifactType: "infra" },
        ]);
      }
    }

    // Residues — planned in parallel (independent, read-only), merged in
    // canonical tool order so the composed plan and any refused defect are
    // deterministic regardless of completion order. They receive the
    // pack-aware context, so installed pack content flows through each
    // adapter's own dialect emission (per-tool rules, agents, commands).
    const settled = await Promise.allSettled(
      tools.map(
        (tool) =>
          residues[tool]?.planResidue(core, residueCtx) ??
          Promise.resolve<ResidueEmission>({ outputs: [] }),
      ),
    );
    // Merged in the same canonical tool order as the rows, and appended AFTER
    // the core findings, so one run's diagnosis reads in the order it was
    // produced rather than in completion order.
    const residueWarnings: string[] = [];
    for (const [index, tool] of tools.entries()) {
      const outcome = settled[index]!;
      if (outcome.status === "rejected") {
        const reason: unknown = outcome.reason;
        throw new EngineError(
          `The "${tool}" residue planner failed while planning its per-client output: ` +
            `${reason instanceof Error ? reason.message : String(reason)}. No files were ` +
            `written. Fix the adapter defect (or deselect the tool) and re-run.`,
          { code: "ADAPTER_ERROR", cause: reason },
        );
      }
      for (const output of outcome.value.outputs) {
        mergeResidueRow(rows, sharedPaths, replacedPaths, tool, output);
      }
      residueWarnings.push(...(outcome.value.warnings ?? []));
    }

    // Last, over the finished row set: the user's pre-existing config files
    // outrank every planner's opinion about the paths they sit on.
    applyImportDecisions(rows, importDecisionsOf(ctx.manifest), ctx.engineVersion);

    const outputs = [...rows.values()]
      .toSorted((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
      .map((row) => {
        const output: AdapterOutput = {
          path: row.path,
          content: row.content,
          owner: row.owners[0]!,
        };
        // Key left absent (not `undefined`-valued) on single-owner rows, so
        // co-owner-unaware consumers see the pre-seam shape byte-for-byte.
        if (row.owners.length > 1) output.coOwners = row.owners.slice(1);
        return output;
      });

    // Copied, not aliased: the plan is handed to a caller that may keep it for
    // the length of a run, and the core plan object is this pass's own.
    return { outputs, warnings: [...core.hooks.warnings, ...residueWarnings] };
  };

  return {
    id: `core+residue[${registered.join(",")}]`,
    plan: async (ctx) => (await planWithWarnings(ctx)).outputs,
    planWithWarnings,
  };
}

/**
 * The context residue planners receive: `ctx` itself for a repo with no pack
 * content (identity preserved, so a no-packs plan is byte-identical to a
 * pack-unaware build), or a derived context whose `contentRoot` carries the
 * installed-pack roots and whose manifest selection also admits the pack
 * artifacts (installed = selected).
 *
 * Widening, never narrowing: the spec is rebuilt part by part, so every part
 * the caller passed in survives the rebuild. The repo's own override tree
 * (`ContentRoots.overrideRoot`) is the one that used to be dropped, and the
 * cost of dropping it was invisible — the customization layer did not error in
 * a pack-having repo, it silently stopped arriving, and where an override held
 * a shipped id the SHIPPED body emitted under it. A part omitted here is a
 * content layer that appears or disappears with unrelated state, which is why
 * the rebuild carries all three rather than the two the pack wiring needed.
 *
 * The derivation is what projects pack content through the per-tool residue
 * surfaces WITHOUT an adapter edit: every adapter already walks
 * `buildContentIndex(ctx.contentRoot)` and filters through the manifest
 * selection, so widening those two inputs is the whole wiring. The rows an
 * adapter emits for pack items carry that adapter as owner — ordinary
 * ADAPTER-owned ledger rows sourced from pack content — which is exactly what
 * makes sync regenerate them and a removed pack's projections reclaimable:
 * the pack's rows vanish from the ledger, the next plan omits the
 * projections, and the reclaim diff sweeps the copies. Pack SOURCE bytes
 * under `.stamity/packs/` are never planned here at all (install-once).
 */
function residueContext(ctx: EmissionContext, packs: ResolvedPackContent): EmissionContext {
  if (packs.items.length === 0) return ctx;
  const spec = contentRootsOf(ctx.contentRoot);
  return {
    ...ctx,
    contentRoot: {
      ...(spec.root === undefined ? {} : { root: spec.root }),
      packRoots: [...spec.packRoots, ...packs.packRoots],
      ...(spec.overrideRoot === undefined ? {} : { overrideRoot: spec.overrideRoot }),
    },
    manifest: selectionWithInstalledPacks(ctx.manifest, packs.items),
  };
}

/**
 * The persisted existing-config decisions, as a list.
 *
 * Read straight off the manifest, with no reshaping: `SetupManifest.importChoice`
 * (`../types/manifest.ts`) holds ONE record per pre-existing instruction file,
 * which is what detection actually returns — a repo carrying `CLAUDE.md` and
 * `.github/copilot-instructions.md` yields two, pinned by
 * `test/cli/commands/initPlan.test.ts`. An absent field is a greenfield repo
 * and means no decisions, not an empty one to invent.
 *
 * The identity is the point. This function used to wrap a single persisted
 * record into a 0-or-1 element array, so {@link applyImportDecisions} — which
 * has always looped — could never receive more than one decision, and every
 * detected path past the first was planned as an ordinary engine-owned row the
 * operator was never asked about. The schema, the init ask, and the manifest
 * composition all carry the list now, so the wrap has nothing left to do.
 */
function importDecisionsOf(manifest: SetupManifest): readonly ImportDecision[] {
  return manifest.importChoice ?? [];
}

/**
 * Execute the persisted existing-config decisions against the
 * planned rows — every decision, not the first one. This is the one place the
 * three modes become behaviour, and it runs over the FINISHED row set so a
 * residue planner cannot reintroduce a path after its decision was applied.
 *
 * - **skip** — the row is dropped. No bytes, and (because the ledger records
 *   only emitted rows) no ownership claim, so `sync` and `check` see a file the
 *   engine does not emit rather than an unowned collision they refuse on.
 * - **supplement** — a block-less row is wrapped in a managed block, which
 *   routes the write through the merge lane: the block lands above the user's
 *   file and every other byte is preserved verbatim. A row that already
 *   carries a block (the `CLAUDE.md` bridge) is already supplementing and is
 *   left alone, which is also what makes a second pass over the same decision
 *   set a no-op.
 * - **replace** — bytes are unchanged here; replacement is a WRITE-lane
 *   decision (force over the user's file behind a verified `.bak`), taken by
 *   `cli/commands/init/apply.ts` on the same manifest record.
 *
 * A decision naming a path this plan does not emit is inert — the file was an
 * instruction file for a client whose adapter emits nothing there, and the
 * honest answer is to leave it alone, which is what emitting nothing does.
 * Decisions are applied in list order; each names its own path, so the order
 * is observable only when two of them name the same one, where last wins.
 */
function applyImportDecisions(
  rows: Map<string, PendingRow>,
  decisions: readonly ImportDecision[],
  engineVersion: string,
): void {
  for (const decision of decisions) applyImportDecision(rows, decision, engineVersion);
}

/** One decision against the row holding its path, if this plan emits that path. */
function applyImportDecision(
  rows: Map<string, PendingRow>,
  decision: ImportDecision,
  engineVersion: string,
): void {
  const row = rows.get(decision.path);
  if (row === undefined) return;
  if (decision.mode === "skip") {
    rows.delete(decision.path);
    return;
  }
  if (decision.mode !== "supplement") return;
  // The markers module's "plain JSON is never wrapped" is an absolute about a
  // format, and this is the site that could break it: the path comes from a
  // persisted record, the row set holds JSON documents (`.claude/settings.json`,
  // the MCP configs), and `getMarkersForPath` answers HTML for an unmapped
  // extension rather than refusing. Wrapping one produced a settings file the
  // client could no longer parse — a supplement that disabled the tool it was
  // supplementing.
  if (!canHostManagedBlock(decision.path)) {
    throw new EngineError(
      `The recorded import decision for "${decision.path}" is "supplement", but that file has no ` +
        `comment syntax to carry a managed block — the markers would make it unparseable for the ` +
        `client that reads it. Record "skip" (leave the file alone) or "replace" (write over it ` +
        `behind a verified .bak) for this path in ${STATE_DIR}/${MANIFEST_FILE}, or remove the ` +
        `decision so the file is emitted normally.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  if (!hasManagedBlock(row.content, decision.path)) {
    row.content = wrapInManagedBlock(row.content, decision.path, engineVersion);
  }
}

/**
 * Insert one row, or merge it into the row already holding its path: equal
 * content unions owners (deduplicated by adapter — ledger row identity is the
 * `(adapter, path)` pair); different content is a refused planner defect that
 * names the path and every claimant, because a silent overwrite here would
 * ship one adapter's bytes under another adapter's ledger row.
 */
function addRow(
  rows: Map<string, PendingRow>,
  path: string,
  content: string,
  owners: readonly EmissionOwner[],
): void {
  const existing = rows.get(path);
  if (existing === undefined) {
    rows.set(path, { path, content, owners: dedupeOwners([], owners) });
    return;
  }
  if (existing.content !== content) {
    const claimants = [...existing.owners, ...owners].map((owner) => owner.adapter).join(", ");
    throw new EngineError(
      `Two planners emitted different content for "${path}" (owners: ${claimants}). ` +
        `One path has one writer: make the emissions byte-identical, or flag the ` +
        `overriding row with replacesSharedPath for a shared core path.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  existing.owners = dedupeOwners(existing.owners, owners);
}

/** Merge one residue output, honouring the shared-path replacement contract. */
function mergeResidueRow(
  rows: Map<string, PendingRow>,
  sharedPaths: ReadonlySet<string>,
  replacedPaths: Set<string>,
  tool: Tool,
  output: AdapterOutput,
): void {
  const owners = outputOwners(output);
  if (output.replacesSharedPath !== true) {
    addRow(rows, output.path, output.content, owners);
    return;
  }
  if (!sharedPaths.has(output.path)) {
    throw new EngineError(
      `The "${tool}" residue planner flagged "${output.path}" with replacesSharedPath, but ` +
        `the core plan does not emit that path as a shared row. Replacement substitutes a ` +
        `co-owned core emission (e.g. the root ${AGENTS_MD_FILE}); emit any other path as a ` +
        `plain residue row instead.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  if (replacedPaths.has(output.path)) {
    throw new EngineError(
      `Two residue planners replaced the shared path "${output.path}" (second: "${tool}"). ` +
        `A shared row takes at most one replacement per plan — one path, one writer.`,
      { code: "VALIDATION_ERROR" },
    );
  }
  replacedPaths.add(output.path);
  const target = rows.get(output.path)!;
  target.content = output.content;
  target.owners = dedupeOwners(target.owners, owners);
}

/** `base` extended with `extra`, first triple per adapter winning, as a fresh array. */
function dedupeOwners(
  base: readonly EmissionOwner[],
  extra: readonly EmissionOwner[],
): EmissionOwner[] {
  const merged: EmissionOwner[] = [];
  const seen = new Set<Tool>();
  for (const owner of [...base, ...extra]) {
    if (seen.has(owner.adapter)) continue;
    seen.add(owner.adapter);
    merged.push({
      adapter: owner.adapter,
      artifactId: owner.artifactId,
      artifactType: owner.artifactType,
    });
  }
  return merged;
}
